using System;
using System.Collections.Generic;
using System.Text;

namespace Tibia
{
    public class Version
    {
        public static void Set(string version)
        {
            #region 8.10 & 8.11 Addresses
            if (version == "8.10" || version == "8.11")
            {
                Addresses.BattleList.Start = 0x613BD0;
                Addresses.BattleList.End = 0x619990;
                Addresses.BattleList.Step_Creatures = 0xA0;
                Addresses.BattleList.Max_Creatures = 100;

                Addresses.Client.StartTime = 0x76D90C;
                Addresses.Client.XTeaKey = 0x768C7C;
                Addresses.Client.FrameRatePointer = 0x76CE0C;
                Addresses.Client.FrameRateCurrentOffset = 0x00;
                Addresses.Client.FrameRateLimitOffset = 0x58;
                Addresses.Client.MultiClient = 0xF8944;
                Addresses.Client.MultiClientValue = 0xEB;
                Addresses.Client.Status = 0x76C2C8;
                Addresses.Client.SafeMode = 0x76909C;
                Addresses.Client.FollowMode = Addresses.Client.SafeMode + 4;
                Addresses.Client.AttackMode = Addresses.Client.FollowMode + 4;
                Addresses.Client.ActionState = 0x76C328;
                Addresses.Client.CurrentWindow = 0x61E984;
                Addresses.Client.LastMSGAuthor = Addresses.Client.LastMSGText - 0x28;
                Addresses.Client.LastMSGText = 0x76DB78;
                Addresses.Client.Statusbar_Text = 0x76D928;
                Addresses.Client.Statusbar_Time = Addresses.Client.Statusbar_Text - 4;
                Addresses.Client.Click_Id = 0x76C364;
                Addresses.Client.Click_Count = Addresses.Client.Click_Id + 4;
                Addresses.Client.Click_Z = Addresses.Client.Click_Id - 0x68;
                Addresses.Client.See_Id = Addresses.Client.Click_Id + 12;
                Addresses.Client.See_Count = Addresses.Client.See_Id + 4;
                Addresses.Client.See_Z = Addresses.Client.See_Id - 0x68;
                Addresses.Client.See_Text = 0x76DB50;
                Addresses.Client.LoginServerStart = 0x763BB8;
                Addresses.Client.Step_LoginServer = 112;
                Addresses.Client.Distance_Port = 100;
                Addresses.Client.Max_LoginServers = 10;
                Addresses.Client.RSA = 0x597610;
                Addresses.Client.LoginCharList = 0x76C288;
                Addresses.Client.GameWindowRectPointer = 0x12D624;
                Addresses.Client.DatPointer = 0x768C9C;
                Addresses.Client.DialogBegin = 0x61E984;
                Addresses.Client.DialogLeft = 0x14;
                Addresses.Client.DialogTop = 0x18;
                Addresses.Client.DialogWidth = 0x1C;
                Addresses.Client.DialogHeight = 0x20;
                Addresses.Client.DialogCaption = 0x50;
                Addresses.Client.LoginAccountNum = 0x76C2C0;
                Addresses.Client.LoginAccountStr = 0x76C2B4;
                Addresses.Client.LoginPassword = 0x76C294;
                Addresses.Client.LoginPatch = 0x47935E;
                Addresses.Client.LoginPatch2 = 0x47A2B3;
                Addresses.Client.LoginPatchOrig = new byte[] { 0xE8, 0x0D, 0x1D, 0x09, 0x00 };
                Addresses.Client.LoginPatchOrig2 = new byte[] { 0xE8, 0xC8, 0x15, 0x09, 0x00 };

                Addresses.Container.Start = 0x61C0D0;
                Addresses.Container.End = 0x61DF90;
                Addresses.Container.Step_Container = 492;
                Addresses.Container.Step_Slot = 12;
                Addresses.Container.Max_Containers = 16;
                Addresses.Container.Max_Stack = 100;
                Addresses.Container.Distance_IsOpen = 0;
                Addresses.Container.Distance_Id = 4;
                Addresses.Container.Distance_Name = 16;
                Addresses.Container.Distance_Volume = 48;
                Addresses.Container.Distance_Amount = 56;
                Addresses.Container.Distance_Item_Id = 60;
                Addresses.Container.Distance_Item_Count = 64;

                Addresses.Creature.Distance_Id = 0;
                Addresses.Creature.Distance_Type = 3;
                Addresses.Creature.Distance_Name = 4;
                Addresses.Creature.Distance_X = 36;
                Addresses.Creature.Distance_Y = 40;
                Addresses.Creature.Distance_Z = 44;
                Addresses.Creature.Distance_ScreenOffsetHoriz = 48;
                Addresses.Creature.Distance_ScreenOffsetVert = 52;
                Addresses.Creature.Distance_IsWalking = 76;
                Addresses.Creature.Distance_WalkSpeed = 140;
                Addresses.Creature.Distance_Direction = 80;
                Addresses.Creature.Distance_IsVisible = 144;
                Addresses.Creature.Distance_BlackSquare = 128;
                Addresses.Creature.Distance_Light = 120;
                Addresses.Creature.Distance_LightColor = 124;
                Addresses.Creature.Distance_HPBar = 136;
                Addresses.Creature.Distance_Skull = 148;
                Addresses.Creature.Distance_Party = 152;
                Addresses.Creature.Distance_Outfit = 96;
                Addresses.Creature.Distance_Color_Head = 100;
                Addresses.Creature.Distance_Color_Body = 104;
                Addresses.Creature.Distance_Color_Legs = 108;
                Addresses.Creature.Distance_Color_Feet = 112;
                Addresses.Creature.Distance_Addon = 116;

                Addresses.DatItem.Width = 0;
                Addresses.DatItem.Height = 4;
                Addresses.DatItem.Unknown1 = 8;
                Addresses.DatItem.Layers = 12;
                Addresses.DatItem.PatternX = 16;
                Addresses.DatItem.PatternY = 20;
                Addresses.DatItem.PatternDepth = 24;
                Addresses.DatItem.Phase = 28;
                Addresses.DatItem.Sprites = 32;
                Addresses.DatItem.Flags = 36;
                Addresses.DatItem.WalkSpeed = 40;
                Addresses.DatItem.TextLimit = 44;
                Addresses.DatItem.LightRadius = 48;
                Addresses.DatItem.LightColor = 52;
                Addresses.DatItem.ShiftX = 56;
                Addresses.DatItem.ShiftY = 60;
                Addresses.DatItem.WalkHeight = 64;
                Addresses.DatItem.Automap = 68;
                Addresses.DatItem.LensHelp = 72;

                Addresses.Hotkey.SendAutomaticallyStart = 0x769298;
                Addresses.Hotkey.SendAutomaticallyStep = 0x01;
                Addresses.Hotkey.TextStart = 0x7692C0;
                Addresses.Hotkey.TextStep = 0x100;
                Addresses.Hotkey.ObjectStart = 0x769208;
                Addresses.Hotkey.ObjectStep = 0x04;
                Addresses.Hotkey.ObjectUseTypeStart = 0x7690E8;
                Addresses.Hotkey.ObjectUseTypeStep = 0x04;
                Addresses.Hotkey.MaxHotkeys = 36;

                Addresses.Map.MapPointer = 0x6234D8;
                Addresses.Map.Step_Square = 172;
                Addresses.Map.Step_Square_Object = 12;
                Addresses.Map.Distance_Square_ObjectCount = 0;
                Addresses.Map.Distance_Square_Objects = 4;
                Addresses.Map.Distance_Object_Id = 0;
                Addresses.Map.Distance_Object_Data = 4;
                Addresses.Map.Distance_Object_Data_Ex = 8;
                Addresses.Map.Max_Square_Objects = 13;
                Addresses.Map.Max_X = 18;
                Addresses.Map.Max_Y = 14;
                Addresses.Map.Max_Z = 8;
                Addresses.Map.Max_Squares = 2016;
                Addresses.Map.Z_Axis_Default = 7;
                Addresses.Map.Player_Tile = 0x3E3A08;
                Addresses.Map.NameSpy1 = 0x4DF469;
                Addresses.Map.NameSpy2 = 0x004DF473;
                Addresses.Map.NameSpy1Default = 19061;
                Addresses.Map.NameSpy2Default = 16501;
                Addresses.Map.LevelSpy1 = 0x4E115A;
                Addresses.Map.LevelSpy2 = 0x4E125F;
                Addresses.Map.LevelSpy3 = 0x4E12E0;
                Addresses.Map.LevelSpyPtr = 0x61B608;
                Addresses.Map.LevelSpyAdd2 = 0x25D8;
                Addresses.Map.RevealInvisible1 = 0x453AF3;
                Addresses.Map.RevealInvisible2 = 0x4DE734;

                Addresses.Player.Flags = 0x00613AF8;
                Addresses.Player.Exp = 0x00613B64; 
                Addresses.Player.Id = Addresses.Player.Exp + 12;
                Addresses.Player.HP = Addresses.Player.Exp + 8;
                Addresses.Player.HP_Max = Addresses.Player.Exp + 4;
                Addresses.Player.Level = Addresses.Player.Exp - 4;
                Addresses.Player.MagicLevel = Addresses.Player.Exp - 8;
                Addresses.Player.Level_Percent = Addresses.Player.Exp - 12;
                Addresses.Player.MagicLevel_Percent = Addresses.Player.Exp - 16;
                Addresses.Player.Mana = Addresses.Player.Exp - 20;
                Addresses.Player.Mana_Max = Addresses.Player.Exp - 24;
                Addresses.Player.Soul = Addresses.Player.Exp - 28;
                Addresses.Player.Stamina = Addresses.Player.Exp - 32;
                Addresses.Player.Cap = Addresses.Player.Exp - 36;
                Addresses.Player.Fist_Percent = 0x00613AFC;
                Addresses.Player.Club_Percent = Addresses.Player.Fist_Percent + 4;
                Addresses.Player.Sword_Percent = Addresses.Player.Fist_Percent + 8;
                Addresses.Player.Axe_Percent = Addresses.Player.Fist_Percent + 12;
                Addresses.Player.Distance_Percent = Addresses.Player.Fist_Percent + 16;
                Addresses.Player.Shielding_Percent = Addresses.Player.Fist_Percent + 20;
                Addresses.Player.Fishing_Percent = Addresses.Player.Fist_Percent + 24;
                Addresses.Player.Fist = Addresses.Player.Fist_Percent + 28;
                Addresses.Player.Club = Addresses.Player.Fist_Percent + 32;
                Addresses.Player.Sword = Addresses.Player.Fist_Percent + 36;
                Addresses.Player.Axe = Addresses.Player.Fist_Percent + 40;
                Addresses.Player.Distance = Addresses.Player.Fist_Percent + 44;
                Addresses.Player.Shielding = Addresses.Player.Fist_Percent + 48;
                Addresses.Player.Fishing = Addresses.Player.Fist_Percent + 52;
                Addresses.Player.Slot_Head = 0x61C058;
                Addresses.Player.Slot_Neck = Addresses.Player.Slot_Head + 12;
                Addresses.Player.Slot_Backpack = Addresses.Player.Slot_Head + 24;
                Addresses.Player.Slot_Armor = Addresses.Player.Slot_Head + 36;
                Addresses.Player.Slot_Right = Addresses.Player.Slot_Head + 48;
                Addresses.Player.Slot_Left = Addresses.Player.Slot_Head + 60;
                Addresses.Player.Slot_Legs = Addresses.Player.Slot_Head + 72;
                Addresses.Player.Slot_Feet = Addresses.Player.Slot_Head + 84;
                Addresses.Player.Slot_Ring = Addresses.Player.Slot_Head + 96;
                Addresses.Player.Slot_Ammo = Addresses.Player.Slot_Head + 108;
                Addresses.Player.Max_Slots = 11;
                Addresses.Player.Distance_Slot_Count = 4;
                Addresses.Player.Slot_Right_Count = Addresses.Player.Slot_Right + 4;
                Addresses.Player.Slot_Left_Count = Addresses.Player.Slot_Left + 4;
                Addresses.Player.Slot_Ammo_Count = Addresses.Player.Slot_Ammo + 4;
                Addresses.Player.CurrentTileToGo = 0x613B78;
                Addresses.Player.TilesToGo = 0x613B7C;
                Addresses.Player.GoTo_X = 0x613BB4;
                Addresses.Player.GoTo_Y = Addresses.Player.GoTo_X - 4;
                Addresses.Player.GoTo_Z = Addresses.Player.GoTo_X - 8;
                Addresses.Player.RedSquare = 0x613B3C;
                Addresses.Player.GreenSquare = Addresses.Player.RedSquare - 4;
                Addresses.Player.WhiteSquare = Addresses.Player.GreenSquare - 8;
                Addresses.Player.AccessN = 0x766DF4;
                Addresses.Player.AccessS = 0x766DC4;
                Addresses.Player.Target_ID = Addresses.Player.RedSquare;
                Addresses.Player.Target_BList_ID = Addresses.Player.Target_ID - 8;
                Addresses.Player.Target_BList_Type = Addresses.Player.Target_ID - 5;
                Addresses.Player.Target_Type = Addresses.Player.Target_ID + 3;
                Addresses.Player.Z = 0x61E9C0;

                Addresses.TextDisplay.PrintName = 0x4E228A;
                Addresses.TextDisplay.PrintFPS = 0x44E753;
                Addresses.TextDisplay.ShowFPS = 0x611874;
                Addresses.TextDisplay.PrintTextFunc = 0x4A3C00;
                Addresses.TextDisplay.NopFPS = 0x44E68F;

                Addresses.Vip.Start = 0x611890;
                Addresses.Vip.End = 0x612128;
                Addresses.Vip.Step_Players = 0x2C;
                Addresses.Vip.Max_Players = 100;
                Addresses.Vip.Distance_Id = 0;
                Addresses.Vip.Distance_Name = 4;
                Addresses.Vip.Distance_Status = 34;
                Addresses.Vip.Distance_Icon = 40;
            }
            #endregion

            #region 8.00 Addresses
            if (version == "8.00")
            {
                Addresses.BattleList.Start = 0x60EB30;
                Addresses.BattleList.End = 0x6148F0;
                Addresses.BattleList.Step_Creatures = 0xA0;
                Addresses.BattleList.Max_Creatures = 100;

                Addresses.Client.XTeaKey = 0x7637AC;
                //Addresses.Client.FrameRate = 0x7661F4; 
                Addresses.Client.MultiClient = 0x4EFB71;
                Addresses.Client.MultiClientValue = 0xEB;
                Addresses.Client.Status = 0x766DF8;
                Addresses.Client.FollowMode = 0x763BD0;
                Addresses.Client.AttackMode = 0x763BD4;
                Addresses.Client.SafeMode = 0x763BCC;
                Addresses.Client.ActionState = 0x751BD8;
                Addresses.Client.CurrentWindow = 0x6198B4;
                Addresses.Client.LastMSGAuthor = 0x768680;
                Addresses.Client.LastMSGText = 0x7686A8;
                Addresses.Client.Statusbar_Text = 0x00768458;
                Addresses.Client.Statusbar_Time = 0x00768454;
                Addresses.Client.Click_Id = 0x766E94;
                Addresses.Client.Click_Count = 0x766E98;
                Addresses.Client.Click_Z = 0x766E2C;
                Addresses.Client.See_Id = 0x766EA0;
                Addresses.Client.See_Count = 0x766EA4;
                Addresses.Client.See_Z = 0x766E00;
                Addresses.Client.LoginServerStart = 0x75EAE8;
                Addresses.Client.Step_LoginServer = 112;
                Addresses.Client.Distance_Port = 100;
                Addresses.Client.Max_LoginServers = 10;
                Addresses.Client.RSA = 0x593610;
                Addresses.Client.LoginCharList = 0x766DBC;
                Addresses.Client.LoginSelectedChar = 0x766DB8;

                Addresses.Container.Start = 0x617000;
                Addresses.Container.End = 0x618EC0;
                Addresses.Container.Step_Container = 492;
                Addresses.Container.Step_Slot = 12;
                Addresses.Container.Max_Containers = 16;
                Addresses.Container.Max_Stack = 100;
                Addresses.Container.Distance_IsOpen = 0;
                Addresses.Container.Distance_Id = 4;
                Addresses.Container.Distance_Name = 16;
                Addresses.Container.Distance_Volume = 48;
                Addresses.Container.Distance_Amount = 56;
                Addresses.Container.Distance_Item_Id = 60;
                Addresses.Container.Distance_Item_Count = 64;

                Addresses.Creature.Distance_Id = 0;
                Addresses.Creature.Distance_Type = 3;
                Addresses.Creature.Distance_Name = 4;
                Addresses.Creature.Distance_X = 36;
                Addresses.Creature.Distance_Y = 40;
                Addresses.Creature.Distance_Z = 44;
                Addresses.Creature.Distance_ScreenOffsetHoriz = 48;
                Addresses.Creature.Distance_ScreenOffsetVert = 52;
                Addresses.Creature.Distance_IsWalking = 76;
                Addresses.Creature.Distance_WalkSpeed = 140;
                Addresses.Creature.Distance_Direction = 80;
                Addresses.Creature.Distance_IsVisible = 144;
                Addresses.Creature.Distance_BlackSquare = 128;
                Addresses.Creature.Distance_Light = 120;
                Addresses.Creature.Distance_LightColor = 124;
                Addresses.Creature.Distance_HPBar = 136;
                Addresses.Creature.Distance_Skull = 148;
                Addresses.Creature.Distance_Party = 152;
                Addresses.Creature.Distance_Outfit = 96;
                Addresses.Creature.Distance_Color_Head = 100;
                Addresses.Creature.Distance_Color_Body = 104;
                Addresses.Creature.Distance_Color_Legs = 108;
                Addresses.Creature.Distance_Color_Feet = 112;
                Addresses.Creature.Distance_Addon = 116;

                Addresses.Map.MapPointer = 0x61E408;
                Addresses.Map.Step_Square = 172;
                Addresses.Map.Step_Square_Object = 12;
                Addresses.Map.Distance_Square_ObjectCount = 0;
                Addresses.Map.Distance_Square_Objects = 4;
                Addresses.Map.Distance_Object_Id = 0;
                Addresses.Map.Distance_Object_Data = 4;
                Addresses.Map.Distance_Object_Data_Ex = 8;
                Addresses.Map.Max_Squares = 2016;
                Addresses.Map.Max_Square_Objects = 13;
                Addresses.Map.Z_Axis_Default = 7;

                Addresses.Player.Flags = 0x60EA58;
                Addresses.Player.Exp = 0x60EAC4;
                Addresses.Player.Id = Addresses.Player.Exp + 12;
                Addresses.Player.HP = Addresses.Player.Exp + 8;
                Addresses.Player.HP_Max = Addresses.Player.Exp + 4;
                Addresses.Player.Level = Addresses.Player.Exp - 4;
                Addresses.Player.MagicLevel = Addresses.Player.Exp - 8;
                Addresses.Player.Level_Percent = Addresses.Player.Exp - 12;
                Addresses.Player.MagicLevel_Percent = Addresses.Player.Exp - 16;
                Addresses.Player.Mana = Addresses.Player.Exp - 20;
                Addresses.Player.Mana_Max = Addresses.Player.Exp - 24;
                Addresses.Player.Soul = Addresses.Player.Exp - 28;
                Addresses.Player.Stamina = Addresses.Player.Exp - 32;
                Addresses.Player.Cap = Addresses.Player.Exp - 36;
                Addresses.Player.Fist_Percent = 0x60EA5C;
                Addresses.Player.Club_Percent = Addresses.Player.Fist_Percent + 4;
                Addresses.Player.Sword_Percent = Addresses.Player.Fist_Percent + 8;
                Addresses.Player.Axe_Percent = Addresses.Player.Fist_Percent + 12;
                Addresses.Player.Distance_Percent = Addresses.Player.Fist_Percent + 16;
                Addresses.Player.Shielding_Percent = Addresses.Player.Fist_Percent + 20;
                Addresses.Player.Fishing_Percent = Addresses.Player.Fist_Percent + 24;
                Addresses.Player.Fist = Addresses.Player.Fist_Percent + 28;
                Addresses.Player.Club = Addresses.Player.Fist_Percent + 32;
                Addresses.Player.Sword = Addresses.Player.Fist_Percent + 36;
                Addresses.Player.Axe = Addresses.Player.Fist_Percent + 40;
                Addresses.Player.Distance = Addresses.Player.Fist_Percent + 44;
                Addresses.Player.Shielding = Addresses.Player.Fist_Percent + 48;
                Addresses.Player.Fishing = Addresses.Player.Fist_Percent + 52;
                Addresses.Player.Slot_Head = 0x616F88;
                Addresses.Player.Slot_Neck = Addresses.Player.Slot_Head + 12;
                Addresses.Player.Slot_Backpack = Addresses.Player.Slot_Head + 24;
                Addresses.Player.Slot_Armor = Addresses.Player.Slot_Head + 36;
                Addresses.Player.Slot_Right = Addresses.Player.Slot_Head + 48;
                Addresses.Player.Slot_Left = Addresses.Player.Slot_Head + 60;
                Addresses.Player.Slot_Legs = Addresses.Player.Slot_Head + 72;
                Addresses.Player.Slot_Feet = Addresses.Player.Slot_Head + 84;
                Addresses.Player.Slot_Ring = Addresses.Player.Slot_Head + 96;
                Addresses.Player.Slot_Ammo = Addresses.Player.Slot_Head + 108;
                Addresses.Player.Distance_Slot_Count = 4;
                Addresses.Player.Slot_Right_Count = Addresses.Player.Slot_Right + 4;
                Addresses.Player.Slot_Left_Count = Addresses.Player.Slot_Left + 4;
                Addresses.Player.Slot_Ammo_Count = Addresses.Player.Slot_Ammo + 4;
                Addresses.Player.GoTo_X = 0x60EB10;
                Addresses.Player.GoTo_Y = Addresses.Player.GoTo_X - 4;
                Addresses.Player.GoTo_Z = Addresses.Player.GoTo_X - 8;
                Addresses.Player.RedSquare = 0x60EA9C;
                Addresses.Player.GreenSquare = Addresses.Player.RedSquare - 4;
                Addresses.Player.WhiteSquare = Addresses.Player.GreenSquare - 8;
                Addresses.Player.AccessN = 0x766DF4;
                Addresses.Player.AccessS = 0x766DC4;
                Addresses.Player.Target_ID = 0x60EA9C;
                Addresses.Player.Target_Type = 0x60EA9F;
                Addresses.Player.Target_BList_ID = 0x60EA94;
                Addresses.Player.Target_BList_Type = 0x60EA97;

                Addresses.Vip.Start = 0x60C7F0;
                Addresses.Vip.End = 0x60C840;
                Addresses.Vip.Step_Players = 0x2C;
                Addresses.Vip.Max_Players = 100;
                Addresses.Vip.Distance_Id = 0;
                Addresses.Vip.Distance_Name = 4;
                Addresses.Vip.Distance_Status = 34;
                Addresses.Vip.Distance_Icon = 40;
                
            }
            #endregion
        }
    }
}
