using System;
using System.Collections.Generic;
using System.Text;
using Tibia.Objects;

namespace Tibia.Constants
{
    /// <summary>
    /// Contains lists of items.
    /// </summary>
    public static class ItemLists
    {
        #region All Items
        public static Dictionary<uint, Item> AllItems = new Dictionary<uint, Item>
        {
            { Items.Armor.FrozenPlate.Id, Items.Armor.FrozenPlate }, 
            { Items.Armor.RangersCloak.Id, Items.Armor.RangersCloak }, 
            { Items.Armor.LavosArmor.Id, Items.Armor.LavosArmor }, 
            { Items.Armor.RobeoftheUnderworld.Id, Items.Armor.RobeoftheUnderworld }, 
            { Items.Armor.MasterArchersArmor.Id, Items.Armor.MasterArchersArmor }, 
            { Items.Armor.FirebornGiantArmor.Id, Items.Armor.FirebornGiantArmor }, 
            { Items.Armor.WindbornColossusArmor.Id, Items.Armor.WindbornColossusArmor }, 
            { Items.Armor.GreenwoodCoat.Id, Items.Armor.GreenwoodCoat }, 
            { Items.Armor.FocusCape.Id, Items.Armor.FocusCape }, 
            { Items.Armor.MagiciansRobe.Id, Items.Armor.MagiciansRobe }, 
            { Items.Armor.HibiscusDress.Id, Items.Armor.HibiscusDress }, 
            { Items.Armor.BeltedCape.Id, Items.Armor.BeltedCape }, 
            { Items.Armor.SkullcrackerArmor.Id, Items.Armor.SkullcrackerArmor }, 
            { Items.Armor.LethalLissysShirt.Id, Items.Armor.LethalLissysShirt }, 
            { Items.Armor.TerraMantle.Id, Items.Armor.TerraMantle }, 
            { Items.Armor.LightningRobe.Id, Items.Armor.LightningRobe }, 
            { Items.Armor.PirateShirt.Id, Items.Armor.PirateShirt }, 
            { Items.Armor.Mammothfurcape.Id, Items.Armor.Mammothfurcape }, 
            { Items.Armor.PlateArmor.Id, Items.Armor.PlateArmor }, 
            { Items.Armor.ChainArmor.Id, Items.Armor.ChainArmor }, 
            { Items.Armor.BrassArmor.Id, Items.Armor.BrassArmor }, 
            { Items.Armor.GoldenArmor.Id, Items.Armor.GoldenArmor }, 
            { Items.Armor.LeatherArmor.Id, Items.Armor.LeatherArmor }, 
            { Items.Armor.MagicPlateArmor.Id, Items.Armor.MagicPlateArmor }, 
            { Items.Armor.KnightArmor.Id, Items.Armor.KnightArmor }, 
            { Items.Armor.ScaleArmor.Id, Items.Armor.ScaleArmor }, 
            { Items.Armor.StuddedArmor.Id, Items.Armor.StuddedArmor }, 
            { Items.Armor.Doublet.Id, Items.Armor.Doublet }, 
            { Items.Armor.NobleArmor.Id, Items.Armor.NobleArmor }, 
            { Items.Armor.CrownArmor.Id, Items.Armor.CrownArmor }, 
            { Items.Armor.DarkArmor.Id, Items.Armor.DarkArmor }, 
            { Items.Armor.DragonScaleMail.Id, Items.Armor.DragonScaleMail }, 
            { Items.Armor.DemonArmor.Id, Items.Armor.DemonArmor }, 
            { Items.Armor.AmazonArmor.Id, Items.Armor.AmazonArmor }, 
            { Items.Armor.NativeArmor.Id, Items.Armor.NativeArmor }, 
            { Items.Armor.LeopardArmor.Id, Items.Armor.LeopardArmor }, 
            { Items.Armor.DwarvenArmor.Id, Items.Armor.DwarvenArmor }, 
            { Items.Armor.BlueRobe.Id, Items.Armor.BlueRobe }, 
            { Items.Armor.RedRobe.Id, Items.Armor.RedRobe }, 
            { Items.Legs.RangerLegs.Id, Items.Legs.RangerLegs }, 
            { Items.Legs.BlueLegs.Id, Items.Legs.BlueLegs }, 
            { Items.Legs.GlacierKilt.Id, Items.Legs.GlacierKilt }, 
            { Items.Legs.LightningLegs.Id, Items.Legs.LightningLegs }, 
            { Items.Legs.StuddedLegs.Id, Items.Legs.StuddedLegs }, 
            { Items.Legs.DragonScaleLegs.Id, Items.Legs.DragonScaleLegs }, 
            { Items.Legs.GoldenLegs.Id, Items.Legs.GoldenLegs }, 
            { Items.Legs.KnightLegs.Id, Items.Legs.KnightLegs }, 
            { Items.Legs.BrassLegs.Id, Items.Legs.BrassLegs }, 
            { Items.Legs.CrownLegs.Id, Items.Legs.CrownLegs }, 
            { Items.Legs.DemonLegs.Id, Items.Legs.DemonLegs }, 
            { Items.Legs.DwarvenLegs.Id, Items.Legs.DwarvenLegs }, 
            { Items.Legs.ElvenLegs.Id, Items.Legs.ElvenLegs }, 
            { Items.Legs.PlateLegs.Id, Items.Legs.PlateLegs }, 
            { Items.Legs.ChainLegs.Id, Items.Legs.ChainLegs }, 
            { Items.Legs.LeatherLegs.Id, Items.Legs.LeatherLegs }, 
            { Items.Helmet.MageHat.Id, Items.Helmet.MageHat }, 
            { Items.Helmet.DwarvenHelmet.Id, Items.Helmet.DwarvenHelmet }, 
            { Items.Helmet.Helmetofthedeep.Id, Items.Helmet.Helmetofthedeep }, 
            { Items.Helmet.Postofficershat.Id, Items.Helmet.Postofficershat }, 
            { Items.Helmet.KrimhornHelmet.Id, Items.Helmet.KrimhornHelmet }, 
            { Items.Helmet.JesterHat.Id, Items.Helmet.JesterHat }, 
            { Items.Helmet.MiningHelmet.Id, Items.Helmet.MiningHelmet }, 
            { Items.Helmet.CharmersTiara.Id, Items.Helmet.CharmersTiara }, 
            { Items.Helmet.TerraHood.Id, Items.Helmet.TerraHood }, 
            { Items.Helmet.GlacierMask.Id, Items.Helmet.GlacierMask }, 
            { Items.Helmet.Bandana.Id, Items.Helmet.Bandana }, 
            { Items.Helmet.SkullHelmet.Id, Items.Helmet.SkullHelmet }, 
            { Items.Helmet.LightningHeadband.Id, Items.Helmet.LightningHeadband }, 
            { Items.Helmet.MagmaMonocle.Id, Items.Helmet.MagmaMonocle }, 
            { Items.Helmet.Helmetoftheancients.Id, Items.Helmet.Helmetoftheancients }, 
            { Items.Helmet.BeholderHelmet.Id, Items.Helmet.BeholderHelmet }, 
            { Items.Helmet.SteelHelmet.Id, Items.Helmet.SteelHelmet }, 
            { Items.Helmet.ChainHelmet.Id, Items.Helmet.ChainHelmet }, 
            { Items.Helmet.IronHelmet.Id, Items.Helmet.IronHelmet }, 
            { Items.Helmet.BrassHelmet.Id, Items.Helmet.BrassHelmet }, 
            { Items.Helmet.LeatherHelmet.Id, Items.Helmet.LeatherHelmet }, 
            { Items.Helmet.DevilHelmet.Id, Items.Helmet.DevilHelmet }, 
            { Items.Helmet.GoldenHelmet.Id, Items.Helmet.GoldenHelmet }, 
            { Items.Helmet.VikingHelmet.Id, Items.Helmet.VikingHelmet }, 
            { Items.Helmet.WingedHelmet.Id, Items.Helmet.WingedHelmet }, 
            { Items.Helmet.WarriorHelmet.Id, Items.Helmet.WarriorHelmet }, 
            { Items.Helmet.LegionHelmet.Id, Items.Helmet.LegionHelmet }, 
            { Items.Helmet.SoldierHelmet.Id, Items.Helmet.SoldierHelmet }, 
            { Items.Helmet.StuddedHelmet.Id, Items.Helmet.StuddedHelmet }, 
            { Items.Helmet.DarkHelmet.Id, Items.Helmet.DarkHelmet }, 
            { Items.Helmet.CrownHelmet.Id, Items.Helmet.CrownHelmet }, 
            { Items.Helmet.DemonHelmet.Id, Items.Helmet.DemonHelmet }, 
            { Items.Helmet.HornedHelmet.Id, Items.Helmet.HornedHelmet }, 
            { Items.Helmet.CrusaderHelmet.Id, Items.Helmet.CrusaderHelmet }, 
            { Items.Helmet.RoyalHelmet.Id, Items.Helmet.RoyalHelmet }, 
            { Items.Helmet.AmazonHelmet.Id, Items.Helmet.AmazonHelmet }, 
            { Items.Helmet.DragonScaleHelmet.Id, Items.Helmet.DragonScaleHelmet }, 
            { Items.Helmet.TribalMask.Id, Items.Helmet.TribalMask }, 
            { Items.Helmet.HorsemanHelmet.Id, Items.Helmet.HorsemanHelmet }, 
            { Items.Helmet.FeatherHeaddress.Id, Items.Helmet.FeatherHeaddress }, 
            { Items.Helmet.FerumbrasHat.Id, Items.Helmet.FerumbrasHat }, 
            { Items.Helmet.MagicianHat.Id, Items.Helmet.MagicianHat }, 
            { Items.Helmet.MysticTurban.Id, Items.Helmet.MysticTurban }, 
            { Items.Helmet.Earmuffs.Id, Items.Helmet.Earmuffs }, 
            { Items.Helmet.HelmetOrnament.Id, Items.Helmet.HelmetOrnament }, 
            { Items.Helmet.LeftHorn.Id, Items.Helmet.LeftHorn }, 
            { Items.Helmet.HelmetAdornment.Id, Items.Helmet.HelmetAdornment }, 
            { Items.Swords.NightmareBlade.Id, Items.Swords.NightmareBlade }, 
            { Items.Swords.EmeraldSword.Id, Items.Swords.EmeraldSword }, 
            { Items.Swords.TemplarScytheblade.Id, Items.Swords.TemplarScytheblade }, 
            { Items.Swords.MercenarySword.Id, Items.Swords.MercenarySword }, 
            { Items.Swords.MysticBlade.Id, Items.Swords.MysticBlade }, 
            { Items.Swords.WyvernFang.Id, Items.Swords.WyvernFang }, 
            { Items.Swords.RelicSword.Id, Items.Swords.RelicSword }, 
            { Items.Swords.Demonragesword.Id, Items.Swords.Demonragesword }, 
            { Items.Swords.HauntedBlade.Id, Items.Swords.HauntedBlade }, 
            { Items.Swords.TheAvenger.Id, Items.Swords.TheAvenger }, 
            { Items.Swords.DragonSlayer.Id, Items.Swords.DragonSlayer }, 
            { Items.Swords.Sword.Id, Items.Swords.Sword }, 
            { Items.Swords.Twohandedsword.Id, Items.Swords.Twohandedsword }, 
            { Items.Swords.Dagger.Id, Items.Swords.Dagger }, 
            { Items.Swords.Spikesword.Id, Items.Swords.Spikesword }, 
            { Items.Swords.Rapier.Id, Items.Swords.Rapier }, 
            { Items.Swords.Sabre.Id, Items.Swords.Sabre }, 
            { Items.Swords.MagicLongsword.Id, Items.Swords.MagicLongsword }, 
            { Items.Swords.FireSword.Id, Items.Swords.FireSword }, 
            { Items.Swords.GiantSword.Id, Items.Swords.GiantSword }, 
            { Items.Swords.CarlinSword.Id, Items.Swords.CarlinSword }, 
            { Items.Swords.IceRapier.Id, Items.Swords.IceRapier }, 
            { Items.Swords.Longsword.Id, Items.Swords.Longsword }, 
            { Items.Swords.MagicSword.Id, Items.Swords.MagicSword }, 
            { Items.Swords.SilverDagger.Id, Items.Swords.SilverDagger }, 
            { Items.Swords.Knife.Id, Items.Swords.Knife }, 
            { Items.Swords.CombatKnife.Id, Items.Swords.CombatKnife }, 
            { Items.Swords.ShortSword.Id, Items.Swords.ShortSword }, 
            { Items.Swords.BrightSword.Id, Items.Swords.BrightSword }, 
            { Items.Swords.WarlordSword.Id, Items.Swords.WarlordSword }, 
            { Items.Swords.SerpentSword.Id, Items.Swords.SerpentSword }, 
            { Items.Swords.PoisonDagger.Id, Items.Swords.PoisonDagger }, 
            { Items.Swords.Katana.Id, Items.Swords.Katana }, 
            { Items.Swords.Broadsword.Id, Items.Swords.Broadsword }, 
            { Items.Swords.Scimitar.Id, Items.Swords.Scimitar }, 
            { Items.Swords.Machete.Id, Items.Swords.Machete }, 
            { Items.Swords.PharaohSword.Id, Items.Swords.PharaohSword }, 
            { Items.Swords.BoneSword.Id, Items.Swords.BoneSword }, 
            { Items.Swords.DjinnBlade.Id, Items.Swords.DjinnBlade }, 
            { Items.Swords.CrystalSword.Id, Items.Swords.CrystalSword }, 
            { Items.Swords.BlacksteelSword.Id, Items.Swords.BlacksteelSword }, 
            { Items.Swords.MysticBladeEnergyenchanted.Id, Items.Swords.MysticBladeEnergyenchanted }, 
            { Items.Swords.MysticBladeFireEnchanted.Id, Items.Swords.MysticBladeFireEnchanted }, 
            { Items.Swords.BlacksteelSwordEnergyenchanted.Id, Items.Swords.BlacksteelSwordEnergyenchanted }, 
            { Items.Swords.BlacksteelSwordEarthEnchanted.Id, Items.Swords.BlacksteelSwordEarthEnchanted }, 
            { Items.Swords.DragonSlayerFireEnchanted.Id, Items.Swords.DragonSlayerFireEnchanted }, 
            { Items.Axes.GloriousAxe.Id, Items.Axes.GloriousAxe }, 
            { Items.Axes.SteelAxe.Id, Items.Axes.SteelAxe }, 
            { Items.Axes.HellforgedAxe.Id, Items.Axes.HellforgedAxe }, 
            { Items.Axes.OrnamentedAxe.Id, Items.Axes.OrnamentedAxe }, 
            { Items.Axes.Headchopper.Id, Items.Axes.Headchopper }, 
            { Items.Axes.NobleAxe.Id, Items.Axes.NobleAxe }, 
            { Items.Axes.DreadedCleaver.Id, Items.Axes.DreadedCleaver }, 
            { Items.Axes.TitanAxe.Id, Items.Axes.TitanAxe }, 
            { Items.Axes.RipperLance.Id, Items.Axes.RipperLance }, 
            { Items.Axes.BeastslayersAxe.Id, Items.Axes.BeastslayersAxe }, 
            { Items.Axes.WarAxe.Id, Items.Axes.WarAxe }, 
            { Items.Axes.TwinAxe.Id, Items.Axes.TwinAxe }, 
            { Items.Axes.DwarvenAxe.Id, Items.Axes.DwarvenAxe }, 
            { Items.Axes.ObsidianLance.Id, Items.Axes.ObsidianLance }, 
            { Items.Axes.Naginata.Id, Items.Axes.Naginata }, 
            { Items.Axes.GuardianHalberd.Id, Items.Axes.GuardianHalberd }, 
            { Items.Axes.OrcishAxe.Id, Items.Axes.OrcishAxe }, 
            { Items.Axes.BarbarianAxe.Id, Items.Axes.BarbarianAxe }, 
            { Items.Axes.KnightAxe.Id, Items.Axes.KnightAxe }, 
            { Items.Axes.StonecuttersAxe.Id, Items.Axes.StonecuttersAxe }, 
            { Items.Axes.FireAxe.Id, Items.Axes.FireAxe }, 
            { Items.Axes.GoldenSickle.Id, Items.Axes.GoldenSickle }, 
            { Items.Axes.DragonLance.Id, Items.Axes.DragonLance }, 
            { Items.Axes.GreatAxe.Id, Items.Axes.GreatAxe }, 
            { Items.Axes.Sickle.Id, Items.Axes.Sickle }, 
            { Items.Axes.BattleAxe.Id, Items.Axes.BattleAxe }, 
            { Items.Axes.HandAxe.Id, Items.Axes.HandAxe }, 
            { Items.Axes.Halberd.Id, Items.Axes.Halberd }, 
            { Items.Axes.Axe.Id, Items.Axes.Axe }, 
            { Items.Axes.Doubleaxe.Id, Items.Axes.Doubleaxe }, 
            { Items.Axes.Hatchet.Id, Items.Axes.Hatchet }, 
            { Items.Axes.WarAxeEarthEnchanted.Id, Items.Axes.WarAxeEarthEnchanted }, 
            { Items.Axes.WarAxeIceEnchanted.Id, Items.Axes.WarAxeIceEnchanted }, 
            { Items.Clubs.DaramianMace.Id, Items.Clubs.DaramianMace }, 
            { Items.Clubs.ObsidianTruncheon.Id, Items.Clubs.ObsidianTruncheon }, 
            { Items.Clubs.AbyssHammer.Id, Items.Clubs.AbyssHammer }, 
            { Items.Clubs.HeavyMace.Id, Items.Clubs.HeavyMace }, 
            { Items.Clubs.SapphireHammer.Id, Items.Clubs.SapphireHammer }, 
            { Items.Clubs.ShadowSceptre.Id, Items.Clubs.ShadowSceptre }, 
            { Items.Clubs.LunarStaff.Id, Items.Clubs.LunarStaff }, 
            { Items.Clubs.AmberStaff.Id, Items.Clubs.AmberStaff }, 
            { Items.Clubs.OrcishMaul.Id, Items.Clubs.OrcishMaul }, 
            { Items.Clubs.TaurusMace.Id, Items.Clubs.TaurusMace }, 
            { Items.Clubs.ChaosMace.Id, Items.Clubs.ChaosMace }, 
            { Items.Clubs.DiamondSceptre.Id, Items.Clubs.DiamondSceptre }, 
            { Items.Clubs.CranialBasher.Id, Items.Clubs.CranialBasher }, 
            { Items.Clubs.DragonboneStaff.Id, Items.Clubs.DragonboneStaff }, 
            { Items.Clubs.BananaStaff.Id, Items.Clubs.BananaStaff }, 
            { Items.Clubs.LicheStaff.Id, Items.Clubs.LicheStaff }, 
            { Items.Clubs.ArcaneStaff.Id, Items.Clubs.ArcaneStaff }, 
            { Items.Clubs.BoneClub.Id, Items.Clubs.BoneClub }, 
            { Items.Clubs.StuddedClub.Id, Items.Clubs.StuddedClub }, 
            { Items.Clubs.CrystalMace.Id, Items.Clubs.CrystalMace }, 
            { Items.Clubs.SkullStaff.Id, Items.Clubs.SkullStaff }, 
            { Items.Clubs.HammerofWrath.Id, Items.Clubs.HammerofWrath }, 
            { Items.Clubs.MagicStaff.Id, Items.Clubs.MagicStaff }, 
            { Items.Clubs.DragonHammer.Id, Items.Clubs.DragonHammer }, 
            { Items.Clubs.ThunderHammer.Id, Items.Clubs.ThunderHammer }, 
            { Items.Clubs.IronHammer.Id, Items.Clubs.IronHammer }, 
            { Items.Clubs.ClericalMace.Id, Items.Clubs.ClericalMace }, 
            { Items.Clubs.SilverMace.Id, Items.Clubs.SilverMace }, 
            { Items.Clubs.Crowbar.Id, Items.Clubs.Crowbar }, 
            { Items.Clubs.BattleHammer.Id, Items.Clubs.BattleHammer }, 
            { Items.Clubs.Staff.Id, Items.Clubs.Staff }, 
            { Items.Clubs.Mace.Id, Items.Clubs.Mace }, 
            { Items.Clubs.MorningStar.Id, Items.Clubs.MorningStar }, 
            { Items.Clubs.Club.Id, Items.Clubs.Club }, 
            { Items.Clubs.Warhammer.Id, Items.Clubs.Warhammer }, 
            { Items.Clubs.FurryClub.Id, Items.Clubs.FurryClub }, 
            { Items.Clubs.WarHammerenergyenchanted.Id, Items.Clubs.WarHammerenergyenchanted }, 
            { Items.Clubs.OrcishmaulEnergyEnchanted.Id, Items.Clubs.OrcishmaulEnergyEnchanted }, 
            { Items.Clubs.OrcishMaulFireenchanted.Id, Items.Clubs.OrcishMaulFireenchanted }, 
            { Items.Clubs.CranialBasherEarthEnchanted.Id, Items.Clubs.CranialBasherEarthEnchanted }, 
            { Items.Clubs.CranialBasherIceEnchanted.Id, Items.Clubs.CranialBasherIceEnchanted }, 
            { Items.Clubs.CranialBasherFireEnchanted.Id, Items.Clubs.CranialBasherFireEnchanted }, 
            { Items.Distance.Arbalest.Id, Items.Distance.Arbalest }, 
            { Items.Distance.ModifiedCrossbow.Id, Items.Distance.ModifiedCrossbow }, 
            { Items.Distance.RoyalCrossbow.Id, Items.Distance.RoyalCrossbow }, 
            { Items.Distance.WarsingerBow.Id, Items.Distance.WarsingerBow }, 
            { Items.Distance.Bow.Id, Items.Distance.Bow }, 
            { Items.Distance.Crossbow.Id, Items.Distance.Crossbow }, 
            { Items.Shield.NorseShield.Id, Items.Shield.NorseShield }, 
            { Items.Shield.SpellbookofDarkMysteries.Id, Items.Shield.SpellbookofDarkMysteries }, 
            { Items.Shield.TortoiseShield.Id, Items.Shield.TortoiseShield }, 
            { Items.Shield.SteelShield.Id, Items.Shield.SteelShield }, 
            { Items.Shield.PlateShield.Id, Items.Shield.PlateShield }, 
            { Items.Shield.BrassShield.Id, Items.Shield.BrassShield }, 
            { Items.Shield.WoodenShield.Id, Items.Shield.WoodenShield }, 
            { Items.Shield.BattleShield.Id, Items.Shield.BattleShield }, 
            { Items.Shield.MastermindShield.Id, Items.Shield.MastermindShield }, 
            { Items.Shield.GuardiansShield.Id, Items.Shield.GuardiansShield }, 
            { Items.Shield.DragonShield.Id, Items.Shield.DragonShield }, 
            { Items.Shield.ShieldofHonour.Id, Items.Shield.ShieldofHonour }, 
            { Items.Shield.BeholderShield.Id, Items.Shield.BeholderShield }, 
            { Items.Shield.CrownShield.Id, Items.Shield.CrownShield }, 
            { Items.Shield.DemonShield.Id, Items.Shield.DemonShield }, 
            { Items.Shield.DarkShield.Id, Items.Shield.DarkShield }, 
            { Items.Shield.GreatShield.Id, Items.Shield.GreatShield }, 
            { Items.Shield.BlessedShield.Id, Items.Shield.BlessedShield }, 
            { Items.Shield.OrnamentedShield.Id, Items.Shield.OrnamentedShield }, 
            { Items.Shield.DwarvenShield.Id, Items.Shield.DwarvenShield }, 
            { Items.Shield.StuddedShield.Id, Items.Shield.StuddedShield }, 
            { Items.Shield.RoseShield.Id, Items.Shield.RoseShield }, 
            { Items.Shield.TowerShield.Id, Items.Shield.TowerShield }, 
            { Items.Shield.BlackShield.Id, Items.Shield.BlackShield }, 
            { Items.Shield.CopperShield.Id, Items.Shield.CopperShield }, 
            { Items.Shield.VikingShield.Id, Items.Shield.VikingShield }, 
            { Items.Shield.AncientShield.Id, Items.Shield.AncientShield }, 
            { Items.Shield.GriffinShield.Id, Items.Shield.GriffinShield }, 
            { Items.Shield.VampireShield.Id, Items.Shield.VampireShield }, 
            { Items.Shield.CastleShield.Id, Items.Shield.CastleShield }, 
            { Items.Shield.MedusaShield.Id, Items.Shield.MedusaShield }, 
            { Items.Shield.AmazonShield.Id, Items.Shield.AmazonShield }, 
            { Items.Shield.EagleShield.Id, Items.Shield.EagleShield }, 
            { Items.Shield.PhoenixShield.Id, Items.Shield.PhoenixShield }, 
            { Items.Shield.ScarabShield.Id, Items.Shield.ScarabShield }, 
            { Items.Shield.BoneShield.Id, Items.Shield.BoneShield }, 
            { Items.Shield.PlasmaShield.Id, Items.Shield.PlasmaShield }, 
            { Items.Shield.TuskShield.Id, Items.Shield.TuskShield }, 
            { Items.Shield.SentinelShield.Id, Items.Shield.SentinelShield }, 
            { Items.Shield.SalamanderShield.Id, Items.Shield.SalamanderShield }, 
            { Items.Shield.SpellbookofEnlightenment.Id, Items.Shield.SpellbookofEnlightenment }, 
            { Items.Ring.SignetRing.Id, Items.Ring.SignetRing }, 
            { Items.Ring.DwarvenRing.Id, Items.Ring.DwarvenRing }, 
            { Items.Ring.MightRing.Id, Items.Ring.MightRing }, 
            { Items.Ring.CrystalRing.Id, Items.Ring.CrystalRing }, 
            { Items.Ring.StealthRing.Id, Items.Ring.StealthRing }, 
            { Items.Ring.PowerRing.Id, Items.Ring.PowerRing }, 
            { Items.Ring.EnergyRing.Id, Items.Ring.EnergyRing }, 
            { Items.Ring.LifeRing.Id, Items.Ring.LifeRing }, 
            { Items.Ring.TimeRing.Id, Items.Ring.TimeRing }, 
            { Items.Ring.AxeRing.Id, Items.Ring.AxeRing }, 
            { Items.Ring.RingOfHealing.Id, Items.Ring.RingOfHealing }, 
            { Items.Ring.RingOfTheSkies.Id, Items.Ring.RingOfTheSkies }, 
            { Items.Ring.ClubRing.Id, Items.Ring.ClubRing }, 
            { Items.Ring.DeathRing.Id, Items.Ring.DeathRing }, 
            { Items.Neck.GlacierAmulet.Id, Items.Neck.GlacierAmulet }, 
            { Items.Neck.Kosheisancientamulet.Id, Items.Neck.Kosheisancientamulet }, 
            { Items.Neck.DemonboneAmulet.Id, Items.Neck.DemonboneAmulet }, 
            { Items.Neck.CrystalNecklace.Id, Items.Neck.CrystalNecklace }, 
            { Items.Neck.BronzeNecklace.Id, Items.Neck.BronzeNecklace }, 
            { Items.Neck.EmeraldBangle.Id, Items.Neck.EmeraldBangle }, 
            { Items.Neck.WolfToothChain.Id, Items.Neck.WolfToothChain }, 
            { Items.Neck.GoldenAmulet.Id, Items.Neck.GoldenAmulet }, 
            { Items.Neck.StarAmulet.Id, Items.Neck.StarAmulet }, 
            { Items.Neck.SilverNecklace.Id, Items.Neck.SilverNecklace }, 
            { Items.Neck.RubyNecklace.Id, Items.Neck.RubyNecklace }, 
            { Items.Neck.ScarabAmulet.Id, Items.Neck.ScarabAmulet }, 
            { Items.Neck.Starlight.Id, Items.Neck.Starlight }, 
            { Items.Neck.AncientAmulet.Id, Items.Neck.AncientAmulet }, 
            { Items.Neck.StrangeTalisman.Id, Items.Neck.StrangeTalisman }, 
            { Items.Neck.SilverAmulet.Id, Items.Neck.SilverAmulet }, 
            { Items.Neck.PlatinumAmulet.Id, Items.Neck.PlatinumAmulet }, 
            { Items.Neck.BronzeAmulet.Id, Items.Neck.BronzeAmulet }, 
            { Items.Neck.AmuletOfLoss.Id, Items.Neck.AmuletOfLoss }, 
            { Items.Neck.BrokenAmulet.Id, Items.Neck.BrokenAmulet }, 
            { Items.Neck.StoneSkinAmulet.Id, Items.Neck.StoneSkinAmulet }, 
            { Items.Neck.ElvenAmulet.Id, Items.Neck.ElvenAmulet }, 
            { Items.Neck.GarlicNecklace.Id, Items.Neck.GarlicNecklace }, 
            { Items.Neck.ProtectionAmulet.Id, Items.Neck.ProtectionAmulet }, 
            { Items.Neck.DragonNecklace.Id, Items.Neck.DragonNecklace }, 
            { Items.Neck.TerraAmulet.Id, Items.Neck.TerraAmulet }, 
            { Items.Neck.Scarf.Id, Items.Neck.Scarf }, 
            { Items.Boots.TerraBoots.Id, Items.Boots.TerraBoots }, 
            { Items.Boots.LightningBoots.Id, Items.Boots.LightningBoots }, 
            { Items.Boots.GlacierBoots.Id, Items.Boots.GlacierBoots }, 
            { Items.Boots.PirateBoots.Id, Items.Boots.PirateBoots }, 
            { Items.Boots.BootsofHaste.Id, Items.Boots.BootsofHaste }, 
            { Items.Boots.LeatherBoots.Id, Items.Boots.LeatherBoots }, 
            { Items.Boots.BunnySlippers.Id, Items.Boots.BunnySlippers }, 
            { Items.Boots.SteelBoots.Id, Items.Boots.SteelBoots }, 
            { Items.Boots.GoldenBoots.Id, Items.Boots.GoldenBoots }, 
            { Items.Boots.CrocodileBoots.Id, Items.Boots.CrocodileBoots }, 
            { Items.Boots.FurBoots.Id, Items.Boots.FurBoots }, 
            { Items.Boots.MagmaBoots.Id, Items.Boots.MagmaBoots }, 
            { Items.Boots.SoftBoots.Id, Items.Boots.SoftBoots }, 
            { Items.Boots.WornSoftBoots.Id, Items.Boots.WornSoftBoots }, 
            { Items.Ammunition.BurstArrow.Id, Items.Ammunition.BurstArrow }, 
            { Items.Ammunition.Arrow.Id, Items.Ammunition.Arrow }, 
            { Items.Ammunition.Bolts.Id, Items.Ammunition.Bolts }, 
            { Items.Ammunition.PoisonArrow.Id, Items.Ammunition.PoisonArrow }, 
            { Items.Ammunition.PowerBolt.Id, Items.Ammunition.PowerBolt }, 
            { Items.Ammunition.CrystalArrow.Id, Items.Ammunition.CrystalArrow }, 
            { Items.Ammunition.SmallStone.Id, Items.Ammunition.SmallStone }, 
            { Items.Ammunition.Spear.Id, Items.Ammunition.Spear }, 
            { Items.Ammunition.RoyalSpear.Id, Items.Ammunition.RoyalSpear }, 
            { Items.Ammunition.ThrowingKnife.Id, Items.Ammunition.ThrowingKnife }, 
            { Items.Ammunition.Snowball.Id, Items.Ammunition.Snowball }, 
            { Items.Ammunition.CobrafangDagger.Id, Items.Ammunition.CobrafangDagger }, 
            { Items.Ammunition.HuntingSpear.Id, Items.Ammunition.HuntingSpear }, 
            { Items.Ammunition.AssassinStar.Id, Items.Ammunition.AssassinStar }, 
            { Items.Ammunition.FlashArrow.Id, Items.Ammunition.FlashArrow }, 
            { Items.Ammunition.EnchantedSpear.Id, Items.Ammunition.EnchantedSpear }, 
            { Items.Ammunition.PiercingBolt.Id, Items.Ammunition.PiercingBolt }, 
            { Items.Ammunition.SniperArrow.Id, Items.Ammunition.SniperArrow }, 
            { Items.Ammunition.EarthArrow.Id, Items.Ammunition.EarthArrow }, 
            { Items.Ammunition.OnyxArrow.Id, Items.Ammunition.OnyxArrow }, 
            { Items.Ammunition.ShiverArrow.Id, Items.Ammunition.ShiverArrow }, 
            { Items.Ammunition.FlamingArrow.Id, Items.Ammunition.FlamingArrow }, 
            { Items.Ammunition.ThrowingStar.Id, Items.Ammunition.ThrowingStar }, 
            { Items.Valuable.GoldCoin.Id, Items.Valuable.GoldCoin }, 
            { Items.Valuable.PlatinumCoin.Id, Items.Valuable.PlatinumCoin }, 
            { Items.Valuable.CrystalCoin.Id, Items.Valuable.CrystalCoin }, 
            { Items.Valuable.ScarabCoin.Id, Items.Valuable.ScarabCoin }, 
            { Items.Valuable.ChristmasToken.Id, Items.Valuable.ChristmasToken }, 
            { Items.Valuable.GiantShimmeringPearlBlue.Id, Items.Valuable.GiantShimmeringPearlBlue }, 
            { Items.Valuable.GiantShimmeringPearlBrown.Id, Items.Valuable.GiantShimmeringPearlBrown }, 
            { Items.Valuable.WhitePearl.Id, Items.Valuable.WhitePearl }, 
            { Items.Valuable.BlackPearl.Id, Items.Valuable.BlackPearl }, 
            { Items.Valuable.OrihalcumPearl.Id, Items.Valuable.OrihalcumPearl }, 
            { Items.Valuable.SmallDiamond.Id, Items.Valuable.SmallDiamond }, 
            { Items.Valuable.SmallSapphire.Id, Items.Valuable.SmallSapphire }, 
            { Items.Valuable.SmallRuby.Id, Items.Valuable.SmallRuby }, 
            { Items.Valuable.SmallEmerald.Id, Items.Valuable.SmallEmerald }, 
            { Items.Valuable.SmallAmethyst.Id, Items.Valuable.SmallAmethyst }, 
            { Items.Valuable.SmallEnchantedSapphire.Id, Items.Valuable.SmallEnchantedSapphire }, 
            { Items.Valuable.SmallEnchantedRuby.Id, Items.Valuable.SmallEnchantedRuby }, 
            { Items.Valuable.SmallEnchantedAmethyst.Id, Items.Valuable.SmallEnchantedAmethyst }, 
            { Items.Valuable.SmallEnchantedEmerald.Id, Items.Valuable.SmallEnchantedEmerald }, 
            { Items.Valuable.Talon.Id, Items.Valuable.Talon }, 
            { Items.Valuable.YellowGem.Id, Items.Valuable.YellowGem }, 
            { Items.Valuable.VioletGem.Id, Items.Valuable.VioletGem }, 
            { Items.Valuable.RedGem.Id, Items.Valuable.RedGem }, 
            { Items.Valuable.GreenGem.Id, Items.Valuable.GreenGem }, 
            { Items.Valuable.BlueGem.Id, Items.Valuable.BlueGem }, 
            { Items.Wand.MagicLightWand.Id, Items.Wand.MagicLightWand }, 
            { Items.Wand.MagicLightWandUsed.Id, Items.Wand.MagicLightWandUsed }, 
            { Items.Wand.CrystalWand.Id, Items.Wand.CrystalWand }, 
            { Items.Wand.WandofInferno.Id, Items.Wand.WandofInferno }, 
            { Items.Wand.WandofDecay.Id, Items.Wand.WandofDecay }, 
            { Items.Wand.WandofCosmicEnergy.Id, Items.Wand.WandofCosmicEnergy }, 
            { Items.Wand.WandofVortex.Id, Items.Wand.WandofVortex }, 
            { Items.Wand.WandofDragonbreath.Id, Items.Wand.WandofDragonbreath }, 
            { Items.Wand.WandofDraconia.Id, Items.Wand.WandofDraconia }, 
            { Items.Wand.WandofVoodoo.Id, Items.Wand.WandofVoodoo }, 
            { Items.Wand.SpellWand.Id, Items.Wand.SpellWand }, 
            { Items.Rod.SnakebiteRod.Id, Items.Rod.SnakebiteRod }, 
            { Items.Rod.MoonlightRod.Id, Items.Rod.MoonlightRod }, 
            { Items.Rod.NecroticRod.Id, Items.Rod.NecroticRod }, 
            { Items.Rod.TerraRod.Id, Items.Rod.TerraRod }, 
            { Items.Rod.HailstormRod.Id, Items.Rod.HailstormRod }, 
            { Items.Rod.UnderworldRod.Id, Items.Rod.UnderworldRod }, 
            { Items.Rod.SpringsproutRod.Id, Items.Rod.SpringsproutRod }, 
            { Items.Rod.NorthwindRod.Id, Items.Rod.NorthwindRod }, 
            { Items.Container.NormalBag.Id, Items.Container.NormalBag }, 
            { Items.Container.GreenBag.Id, Items.Container.GreenBag }, 
            { Items.Container.YellowBag.Id, Items.Container.YellowBag }, 
            { Items.Container.RedBag.Id, Items.Container.RedBag }, 
            { Items.Container.PurpleBag.Id, Items.Container.PurpleBag }, 
            { Items.Container.BlueBag.Id, Items.Container.BlueBag }, 
            { Items.Container.GreyBag.Id, Items.Container.GreyBag }, 
            { Items.Container.GoldenBag.Id, Items.Container.GoldenBag }, 
            { Items.Container.BrocadeBackpack.Id, Items.Container.BrocadeBackpack }, 
            { Items.Container.NormalBackpack.Id, Items.Container.NormalBackpack }, 
            { Items.Container.GreenBackpack.Id, Items.Container.GreenBackpack }, 
            { Items.Container.YellowBackpack.Id, Items.Container.YellowBackpack }, 
            { Items.Container.RedBackpack.Id, Items.Container.RedBackpack }, 
            { Items.Container.PurpleBackpack.Id, Items.Container.PurpleBackpack }, 
            { Items.Container.BlueBackpack.Id, Items.Container.BlueBackpack }, 
            { Items.Container.GreyBackpack.Id, Items.Container.GreyBackpack }, 
            { Items.Container.GoldenBackpack.Id, Items.Container.GoldenBackpack }, 
            { Items.Container.MoonBackpack.Id, Items.Container.MoonBackpack }, 
            { Items.Container.BackpackOfHolding.Id, Items.Container.BackpackOfHolding }, 
            { Items.Container.PirateBackpack.Id, Items.Container.PirateBackpack }, 
            { Items.Container.KeyRing.Id, Items.Container.KeyRing }, 
            { Items.Container.Parcel.Id, Items.Container.Parcel }, 
            { Items.Container.StamppedParcel.Id, Items.Container.StamppedParcel }, 
            { Items.Quest.PieceofMassacresShell.Id, Items.Quest.PieceofMassacresShell }, 
            { Items.Quest.SoulStone.Id, Items.Quest.SoulStone }, 
            { Items.Quest.NoseRing.Id, Items.Quest.NoseRing }, 
            { Items.Quest.Mandrake.Id, Items.Quest.Mandrake }, 
            { Items.Quest.CockroachLeg.Id, Items.Quest.CockroachLeg }, 
            { Items.Quest.SniperGloves.Id, Items.Quest.SniperGloves }, 
            { Items.Quest.LizardLeather.Id, Items.Quest.LizardLeather }, 
            { Items.Quest.GreenDragonLeather.Id, Items.Quest.GreenDragonLeather }, 
            { Items.Quest.MinotaurLeather.Id, Items.Quest.MinotaurLeather }, 
            { Items.Quest.SpiderSilk.Id, Items.Quest.SpiderSilk }, 
            { Items.Quest.IronOre.Id, Items.Quest.IronOre }, 
            { Items.Quest.LizardScale.Id, Items.Quest.LizardScale }, 
            { Items.Quest.RedDragonScale.Id, Items.Quest.RedDragonScale }, 
            { Items.Quest.ApeFur.Id, Items.Quest.ApeFur }, 
            { Items.Quest.ChickenFeather.Id, Items.Quest.ChickenFeather }, 
            { Items.Quest.BehemothFang.Id, Items.Quest.BehemothFang }, 
            { Items.Quest.BatWing.Id, Items.Quest.BatWing }, 
            { Items.Quest.FishFin.Id, Items.Quest.FishFin }, 
            { Items.Quest.BearPaw.Id, Items.Quest.BearPaw }, 
            { Items.Quest.WolfPaw.Id, Items.Quest.WolfPaw }, 
            { Items.Quest.BeholderEye.Id, Items.Quest.BeholderEye }, 
            { Items.Quest.TurtleShells.Id, Items.Quest.TurtleShells }, 
            { Items.Quest.HoneyComb.Id, Items.Quest.HoneyComb }, 
            { Items.Quest.MagicSulphur.Id, Items.Quest.MagicSulphur }, 
            { Items.Quest.VampireDust.Id, Items.Quest.VampireDust }, 
            { Items.Quest.DemonDust.Id, Items.Quest.DemonDust }, 
            { Items.Quest.WhitePieceofCloth.Id, Items.Quest.WhitePieceofCloth }, 
            { Items.Quest.GreenPieceofCloth.Id, Items.Quest.GreenPieceofCloth }, 
            { Items.Quest.RedPieceofCloth.Id, Items.Quest.RedPieceofCloth }, 
            { Items.Quest.BluePieceofCloth.Id, Items.Quest.BluePieceofCloth }, 
            { Items.Quest.BrownPieceofCloth.Id, Items.Quest.BrownPieceofCloth }, 
            { Items.Quest.YellowPieceofCloth.Id, Items.Quest.YellowPieceofCloth }, 
            { Items.Quest.DragonClaw.Id, Items.Quest.DragonClaw }, 
            { Items.Quest.GreenDragonScale.Id, Items.Quest.GreenDragonScale }, 
            { Items.Quest.HeavenBlossom.Id, Items.Quest.HeavenBlossom }, 
            { Items.Quest.HolyOrchid.Id, Items.Quest.HolyOrchid }, 
            { Items.Quest.HardenedBone.Id, Items.Quest.HardenedBone }, 
            { Items.Quest.BehemothClaw.Id, Items.Quest.BehemothClaw }, 
            { Items.Quest.DemonHorn.Id, Items.Quest.DemonHorn }, 
            { Items.Quest.RedDragonLeather.Id, Items.Quest.RedDragonLeather }, 
            { Items.Quest.Hook.Id, Items.Quest.Hook }, 
            { Items.Quest.EyePatch.Id, Items.Quest.EyePatch }, 
            { Items.Quest.PegLeg.Id, Items.Quest.PegLeg }, 
            { Items.Quest.VampireLordToken.Id, Items.Quest.VampireLordToken }, 
            { Items.Quest.Wood.Id, Items.Quest.Wood }, 
            { Items.Tool.ButterflyConservationkit.Id, Items.Tool.ButterflyConservationkit }, 
            { Items.Tool.BotanistsContainer.Id, Items.Tool.BotanistsContainer }, 
            { Items.Tool.Dice.Id, Items.Tool.Dice }, 
            { Items.Tool.FirstMusicSheet.Id, Items.Tool.FirstMusicSheet }, 
            { Items.Tool.SecondMusicSheet.Id, Items.Tool.SecondMusicSheet }, 
            { Items.Tool.ThirdMusicSheet.Id, Items.Tool.ThirdMusicSheet }, 
            { Items.Tool.FourthMusicSheet.Id, Items.Tool.FourthMusicSheet }, 
            { Items.Tool.Worms.Id, Items.Tool.Worms }, 
            { Items.Tool.FrozenStarlight.Id, Items.Tool.FrozenStarlight }, 
            { Items.Tool.ObsidianKnife.Id, Items.Tool.ObsidianKnife }, 
            { Items.Tool.PiggyBank.Id, Items.Tool.PiggyBank }, 
            { Items.Tool.Shard.Id, Items.Tool.Shard }, 
            { Items.Tool.CeremonialAnkh.Id, Items.Tool.CeremonialAnkh }, 
            { Items.Tool.BlessedWoodenStake.Id, Items.Tool.BlessedWoodenStake }, 
            { Items.Tool.WoodenHammer.Id, Items.Tool.WoodenHammer }, 
            { Items.Tool.WateringCan.Id, Items.Tool.WateringCan }, 
            { Items.Tool.Firebug.Id, Items.Tool.Firebug }, 
            { Items.Tool.Spoon.Id, Items.Tool.Spoon }, 
            { Items.Tool.ElvenhairRope.Id, Items.Tool.ElvenhairRope }, 
            { Items.Tool.LockPick.Id, Items.Tool.LockPick }, 
            { Items.Tool.Rope.Id, Items.Tool.Rope }, 
            { Items.Tool.Shovel.Id, Items.Tool.Shovel }, 
            { Items.Tool.LightShovel.Id, Items.Tool.LightShovel }, 
            { Items.Tool.Pick.Id, Items.Tool.Pick }, 
            { Items.Decoration.OracleFigurine.Id, Items.Decoration.OracleFigurine }, 
            { Items.Decoration.SmallOilLamp.Id, Items.Decoration.SmallOilLamp }, 
            { Items.Decoration.VoodooDollPirate.Id, Items.Decoration.VoodooDollPirate }, 
            { Items.Decoration.VoodooDollDworcs.Id, Items.Decoration.VoodooDollDworcs }, 
            { Items.Decoration.Lifecrystal.Id, Items.Decoration.Lifecrystal }, 
            { Items.Decoration.IceCube.Id, Items.Decoration.IceCube }, 
            { Items.Decoration.CyclopsTrophy.Id, Items.Decoration.CyclopsTrophy }, 
            { Items.Decoration.MinotaurTrophy.Id, Items.Decoration.MinotaurTrophy }, 
            { Items.Decoration.DeerTrophy.Id, Items.Decoration.DeerTrophy }, 
            { Items.Decoration.DragonLordTrophy.Id, Items.Decoration.DragonLordTrophy }, 
            { Items.Decoration.LionTrophy.Id, Items.Decoration.LionTrophy }, 
            { Items.Decoration.WolfTrophy.Id, Items.Decoration.WolfTrophy }, 
            { Items.Decoration.MarlinTrophy.Id, Items.Decoration.MarlinTrophy }, 
            { Items.Decoration.OrcTrophy.Id, Items.Decoration.OrcTrophy }, 
            { Items.Decoration.DemonTrophy.Id, Items.Decoration.DemonTrophy }, 
            { Items.Decoration.DwarvenBeard.Id, Items.Decoration.DwarvenBeard }, 
            { Items.Decoration.StuffedDragon.Id, Items.Decoration.StuffedDragon }, 
            { Items.Decoration.BabySealDoll.Id, Items.Decoration.BabySealDoll }, 
            { Items.Decoration.MysteriousVoodooSkull.Id, Items.Decoration.MysteriousVoodooSkull }, 
            { Items.Decoration.PandaTeddy.Id, Items.Decoration.PandaTeddy }, 
            { Items.Decoration.CertificatefromDreamersChallenge.Id, Items.Decoration.CertificatefromDreamersChallenge }, 
            { Items.Decoration.BloodHerb.Id, Items.Decoration.BloodHerb }, 
            { Items.Decoration.SkeletonDecoration.Id, Items.Decoration.SkeletonDecoration }, 
            { Items.Decoration.BatDecoration.Id, Items.Decoration.BatDecoration }, 
            { Items.Decoration.PirateTapestry.Id, Items.Decoration.PirateTapestry }, 
            { Items.Decoration.BlueRose.Id, Items.Decoration.BlueRose }, 
            { Items.Decoration.Firlefanz.Id, Items.Decoration.Firlefanz }, 
            { Items.Decoration.GreenBalloons.Id, Items.Decoration.GreenBalloons }, 
            { Items.Decoration.RedBalloons.Id, Items.Decoration.RedBalloons }, 
            { Items.Decoration.GemmedLamp.Id, Items.Decoration.GemmedLamp }, 
            { Items.Decoration.BlueJewelCase.Id, Items.Decoration.BlueJewelCase }, 
            { Items.Decoration.RedJewelCase.Id, Items.Decoration.RedJewelCase }, 
            { Items.Decoration.SantaDoll.Id, Items.Decoration.SantaDoll }, 
            { Items.Decoration.ModelShip.Id, Items.Decoration.ModelShip }, 
            { Items.Decoration.JesterStaff.Id, Items.Decoration.JesterStaff }, 
            { Items.Decoration.IceMammoth.Id, Items.Decoration.IceMammoth }, 
            { Items.Decoration.WallPicturetheonewithgold.Id, Items.Decoration.WallPicturetheonewithgold }, 
            { Items.Decoration.WallPicturetheportrait.Id, Items.Decoration.WallPicturetheportrait }, 
            { Items.Decoration.WallmirrorRound.Id, Items.Decoration.WallmirrorRound }, 
            { Items.Decoration.TearofDaraman.Id, Items.Decoration.TearofDaraman }, 
            { Items.Decoration.Spyreport.Id, Items.Decoration.Spyreport }, 
            { Items.Decoration.CuckooClock.Id, Items.Decoration.CuckooClock }, 
            { Items.Decoration.FrostCharm.Id, Items.Decoration.FrostCharm }, 
            { Items.Decoration.CrystalBall.Id, Items.Decoration.CrystalBall }, 
            { Items.Decoration.GoldenFigurine.Id, Items.Decoration.GoldenFigurine }, 
            { Items.Decoration.ImperorsTrident.Id, Items.Decoration.ImperorsTrident }, 
            { Items.Decoration.ChristmasBranch.Id, Items.Decoration.ChristmasBranch }, 
            { Items.Decoration.YellowRose.Id, Items.Decoration.YellowRose }, 
            { Items.Decoration.SilkyTapestry.Id, Items.Decoration.SilkyTapestry }, 
            { Items.Decoration.DracoyleStatueEnchanted.Id, Items.Decoration.DracoyleStatueEnchanted }, 
            { Items.Potion.Health.Id, Items.Potion.Health }, 
            { Items.Potion.StrongHealth.Id, Items.Potion.StrongHealth }, 
            { Items.Potion.GreatHealth.Id, Items.Potion.GreatHealth }, 
            { Items.Potion.UltimateHealth.Id, Items.Potion.UltimateHealth }, 
            { Items.Potion.Mana.Id, Items.Potion.Mana }, 
            { Items.Potion.StrongMana.Id, Items.Potion.StrongMana }, 
            { Items.Potion.GreatMana.Id, Items.Potion.GreatMana }, 
            { Items.Potion.GreatSpirit.Id, Items.Potion.GreatSpirit }, 
            { Items.Potion.Bullseye.Id, Items.Potion.Bullseye }, 
            { Items.Potion.Mastermind.Id, Items.Potion.Mastermind }, 
            { Items.Potion.Berserk.Id, Items.Potion.Berserk }, 
            { Items.Bottle.Vial.Id, Items.Bottle.Vial }, 
            { Items.Misc.EternalFlames.Id, Items.Misc.EternalFlames }, 
            { Items.Misc.ToyMouse.Id, Items.Misc.ToyMouse }, 
            { Items.Misc.SpecialFlask.Id, Items.Misc.SpecialFlask }, 
            { Items.Misc.Tusk.Id, Items.Misc.Tusk }, 
            { Items.Misc.Seeds.Id, Items.Misc.Seeds }, 
            { Items.Misc.PurpleTome.Id, Items.Misc.PurpleTome }, 
            { Items.Misc.RedTome.Id, Items.Misc.RedTome }, 
            { Items.Misc.GreenTome.Id, Items.Misc.GreenTome }, 
            { Items.Misc.GoldenGobletFromsvararena.Id, Items.Misc.GoldenGobletFromsvararena }, 
            { Items.Misc.SilverGobletFromsvararena.Id, Items.Misc.SilverGobletFromsvararena }, 
            { Items.Misc.BronzeGobletFromsvararena.Id, Items.Misc.BronzeGobletFromsvararena }, 
            { Items.Misc.DemonicEssence.Id, Items.Misc.DemonicEssence }, 
            { Items.Misc.CatsPaw.Id, Items.Misc.CatsPaw }, 
            { Items.Misc.HydraEgg.Id, Items.Misc.HydraEgg }, 
            { Items.Misc.GoldenMug.Id, Items.Misc.GoldenMug }, 
            { Items.Misc.Marlin.Id, Items.Misc.Marlin }, 
            { Items.Misc.SoulOrb.Id, Items.Misc.SoulOrb }, 
            { Items.Misc.BlueSurpriseBag.Id, Items.Misc.BlueSurpriseBag }, 
            { Items.Misc.RedSurpriseBag.Id, Items.Misc.RedSurpriseBag }, 
            { Items.Misc.MeadHorn.Id, Items.Misc.MeadHorn }, 
            { Items.Misc.MysteriousPackage.Id, Items.Misc.MysteriousPackage }, 
            { Items.Misc.GoldfishBowlgoldfishinit.Id, Items.Misc.GoldfishBowlgoldfishinit }, 
            { Items.Misc.AnnihilationBear.Id, Items.Misc.AnnihilationBear }, 
            { Items.Misc.PhoenixEgg.Id, Items.Misc.PhoenixEgg }, 
            { Items.Misc.TechnomancerBeard.Id, Items.Misc.TechnomancerBeard }, 
            { Items.Misc.ChristmasCard.Id, Items.Misc.ChristmasCard }, 
            { Items.Misc.DocumentoftheLeader.Id, Items.Misc.DocumentoftheLeader }, 
            { Items.Misc.DocumentoftheOfficer.Id, Items.Misc.DocumentoftheOfficer }, 
            { Items.Misc.SkullofRatha.Id, Items.Misc.SkullofRatha }, 
            { Items.Misc.EctoplasmContainer.Id, Items.Misc.EctoplasmContainer }, 
            { Items.Misc.BlessedAnkh.Id, Items.Misc.BlessedAnkh }, 
            { Items.Misc.Lute.Id, Items.Misc.Lute }, 
            { Items.Misc.Inkwell.Id, Items.Misc.Inkwell }, 
            { Items.Misc.ValentineCard.Id, Items.Misc.ValentineCard }, 
            { Items.Misc.WarHorn.Id, Items.Misc.WarHorn }, 
            { Items.Misc.Contract.Id, Items.Misc.Contract }, 
            { Items.Misc.MapBrownbroadone.Id, Items.Misc.MapBrownbroadone }, 
            { Items.Misc.MapSmall.Id, Items.Misc.MapSmall }, 
            { Items.Plant.HoneyFlower.Id, Items.Plant.HoneyFlower }, 
            { Items.Plant.FlowerBowl.Id, Items.Plant.FlowerBowl }, 
            { Items.Plant.FlowerBouquet.Id, Items.Plant.FlowerBouquet }, 
            { Items.Plant.Tulip.Id, Items.Plant.Tulip }, 
            { Items.Plant.GraveFlower.Id, Items.Plant.GraveFlower }, 
            { Items.Plant.OrangeStar.Id, Items.Plant.OrangeStar }, 
            { Items.Plant.MoonFlower.Id, Items.Plant.MoonFlower }, 
            { Items.Plant.PurpleKissBlossom.Id, Items.Plant.PurpleKissBlossom }, 

			
			{ Items.Food.Apple.Id, Items.Food.Apple }, 
			{ Items.Food.Banana.Id, Items.Food.Banana }, 
			{ Items.Food.Blueberry.Id, Items.Food.Blueberry }, 
			{ Items.Food.Bread.Id, Items.Food.Bread }, 
			{ Items.Food.BrownBread.Id, Items.Food.BrownBread }, 
			{ Items.Food.BrownMushroom.Id, Items.Food.BrownMushroom }, 
			{ Items.Food.Carrot.Id, Items.Food.Carrot }, 
			{ Items.Food.Cheese.Id, Items.Food.Cheese }, 
			{ Items.Food.Cherry.Id, Items.Food.Cherry }, 
			{ Items.Food.Coconut.Id, Items.Food.Coconut }, 
			{ Items.Food.Cookie.Id, Items.Food.Cookie }, 
			{ Items.Food.Corncob.Id, Items.Food.Corncob }, 
			{ Items.Food.DragonHam.Id, Items.Food.DragonHam }, 
			{ Items.Food.Egg.Id, Items.Food.Egg }, 
			{ Items.Food.Fish.Id, Items.Food.Fish }, 
			{ Items.Food.Grapes.Id, Items.Food.Grapes }, 
			{ Items.Food.GreenMushroom.Id, Items.Food.GreenMushroom }, 
			{ Items.Food.Ham.Id, Items.Food.Ham }, 
			{ Items.Food.Meat.Id, Items.Food.Meat }, 
			{ Items.Food.Mellon.Id, Items.Food.Mellon }, 
			{ Items.Food.Orange.Id, Items.Food.Orange }, 
			{ Items.Food.Roll.Id, Items.Food.Roll }, 
			{ Items.Food.Salmon.Id, Items.Food.Salmon }, 
			{ Items.Food.WhiteMushroom.Id, Items.Food.WhiteMushroom },
						
			{ Items.Rune.AnimateDead.Id, Items.Rune.AnimateDead },
			{ Items.Rune.Antidote.Id, Items.Rune.Antidote },
			{ Items.Rune.Avalanche.Id, Items.Rune.Avalanche },
			{ Items.Rune.Chameleon.Id, Items.Rune.Chameleon },
			{ Items.Rune.ConvinceCreature.Id, Items.Rune.ConvinceCreature },
			{ Items.Rune.Desintegrate.Id, Items.Rune.Desintegrate },
			{ Items.Rune.DestroyField.Id, Items.Rune.DestroyField },
			{ Items.Rune.EnergyBomb.Id, Items.Rune.EnergyBomb },
			{ Items.Rune.EnergyField.Id, Items.Rune.EnergyField },
			{ Items.Rune.EnergyWall.Id, Items.Rune.EnergyWall },
			{ Items.Rune.Explosion.Id, Items.Rune.Explosion },
			{ Items.Rune.FireBomb.Id, Items.Rune.FireBomb },
			{ Items.Rune.FireField.Id, Items.Rune.FireField },
			{ Items.Rune.FireWall.Id, Items.Rune.FireWall },
			{ Items.Rune.Fireball.Id, Items.Rune.Fireball },
			{ Items.Rune.GreatFireball.Id, Items.Rune.GreatFireball },
			{ Items.Rune.HeavyMagicMissile.Id, Items.Rune.HeavyMagicMissile },
			{ Items.Rune.Icicle.Id, Items.Rune.Icicle },
			{ Items.Rune.IntenseHealing.Id, Items.Rune.IntenseHealing },
			{ Items.Rune.LightMagicMissile.Id, Items.Rune.LightMagicMissile },
			{ Items.Rune.MagicWall.Id, Items.Rune.MagicWall },
			{ Items.Rune.Paralyze.Id, Items.Rune.Paralyze },
			{ Items.Rune.PoisonBomb.Id, Items.Rune.PoisonBomb },
			{ Items.Rune.PoisonField.Id, Items.Rune.PoisonField },
			{ Items.Rune.PoisonWall.Id, Items.Rune.PoisonWall },
			{ Items.Rune.Soulfire.Id, Items.Rune.Soulfire },
			{ Items.Rune.Stalagmite.Id, Items.Rune.Stalagmite },
			{ Items.Rune.StoneShower.Id, Items.Rune.StoneShower },
			{ Items.Rune.SuddenDeath.Id, Items.Rune.SuddenDeath },
			{ Items.Rune.Thunderstorm.Id, Items.Rune.Thunderstorm },
			{ Items.Rune.UltimateHealing.Id, Items.Rune.UltimateHealing },
        };
        #endregion

        #region Ammunitions
        public static Dictionary<uint, Item> Ammunitions = new Dictionary<uint, Item>
        {
			{ Items.Ammunition.Arrow.Id, Items.Ammunition.Arrow },
			{ Items.Ammunition.Bolts.Id, Items.Ammunition.Bolts },
			{ Items.Ammunition.BurstArrow.Id, Items.Ammunition.BurstArrow },
			{ Items.Ammunition.EarthArrow.Id, Items.Ammunition.EarthArrow },
			{ Items.Ammunition.EnchantedSpear.Id, Items.Ammunition.EnchantedSpear },
			{ Items.Ammunition.FlamingArrow.Id, Items.Ammunition.FlamingArrow },
			{ Items.Ammunition.FlashArrow.Id, Items.Ammunition.FlashArrow },
			{ Items.Ammunition.HuntingSpear.Id, Items.Ammunition.HuntingSpear },
			{ Items.Ammunition.PiercingBolt.Id, Items.Ammunition.PiercingBolt },
			{ Items.Ammunition.PoisonArrow.Id, Items.Ammunition.PoisonArrow },
			{ Items.Ammunition.PowerBolt.Id, Items.Ammunition.PowerBolt },
			{ Items.Ammunition.RoyalSpear.Id, Items.Ammunition.RoyalSpear },
			{ Items.Ammunition.ShiverArrow.Id, Items.Ammunition.ShiverArrow },
			{ Items.Ammunition.SmallStone.Id, Items.Ammunition.SmallStone },
			{ Items.Ammunition.SniperArrow.Id, Items.Ammunition.SniperArrow },
			{ Items.Ammunition.Spear.Id, Items.Ammunition.Spear },
			{ Items.Ammunition.ThrowingKnife.Id, Items.Ammunition.ThrowingKnife },
			{ Items.Ammunition.ThrowingStar.Id, Items.Ammunition.ThrowingStar },
        };
        #endregion

        #region Necks
        public static Dictionary<uint, Item> Necks = new Dictionary<uint, Item>
        {
			{ Items.Neck.AmuletOfLoss.Id, Items.Neck.AmuletOfLoss },
			{ Items.Neck.BronzeAmulet.Id, Items.Neck.BronzeAmulet },
			{ Items.Neck.BronzeNecklace.Id, Items.Neck.BronzeNecklace },
			{ Items.Neck.CrystalNecklace.Id, Items.Neck.CrystalNecklace },
			{ Items.Neck.DragonNecklace.Id, Items.Neck.DragonNecklace },
			{ Items.Neck.ElvenAmulet.Id, Items.Neck.ElvenAmulet },
			{ Items.Neck.GarlicNecklace.Id, Items.Neck.GarlicNecklace },
			{ Items.Neck.GoldenAmulet.Id, Items.Neck.GoldenAmulet },
			{ Items.Neck.PlatinumAmulet.Id, Items.Neck.PlatinumAmulet },
			{ Items.Neck.ProtectionAmulet.Id, Items.Neck.ProtectionAmulet },
			{ Items.Neck.Scarf.Id, Items.Neck.Scarf },
			{ Items.Neck.SilverAmulet.Id, Items.Neck.SilverAmulet },
			{ Items.Neck.StarAmulet.Id, Items.Neck.StarAmulet },
			{ Items.Neck.StoneSkinAmulet.Id, Items.Neck.StoneSkinAmulet },
			{ Items.Neck.StrangeTalisman.Id, Items.Neck.StrangeTalisman },
			{ Items.Neck.WolfToothChain.Id, Items.Neck.WolfToothChain },
        };
        #endregion

        #region Containers
        public static Dictionary<uint, Item> Containers = new Dictionary<uint, Item>
        {
			{ Items.Container.GreyBackpack.Id, Items.Container.GreyBackpack },
            { Items.Container.CamouflageBackpack.Id, Items.Container.CamouflageBackpack },
			{ Items.Container.BlueBackpack.Id, Items.Container.BlueBackpack },
			{ Items.Container.NormalBackpack.Id, Items.Container.NormalBackpack },
            { Items.Container.BrocadeBackpack.Id, Items.Container.BrocadeBackpack },
			{ Items.Container.GoldenBackpack.Id, Items.Container.GoldenBackpack },
			{ Items.Container.GreenBackpack.Id, Items.Container.GreenBackpack },
            { Items.Container.MoonBackpack.Id, Items.Container.MoonBackpack },
            { Items.Container.BackpackOfHolding.Id, Items.Container.BackpackOfHolding },
			{ Items.Container.PirateBackpack.Id, Items.Container.PirateBackpack },
			{ Items.Container.PurpleBackpack.Id, Items.Container.PurpleBackpack },
			{ Items.Container.RedBackpack.Id, Items.Container.RedBackpack },
			{ Items.Container.BeachBackpack.Id, Items.Container.BeachBackpack },
			{ Items.Container.YellowBackpack.Id, Items.Container.YellowBackpack },
            { Items.Container.KeyRing.Id, Items.Container.KeyRing },
			{ Items.Container.Parcel.Id, Items.Container.Parcel },
			{ Items.Container.StamppedParcel.Id, Items.Container.StamppedParcel },
            { Items.Container.BlueBag.Id, Items.Container.BlueBag },
            { Items.Container.NormalBag.Id, Items.Container.NormalBag },
            { Items.Container.GreenBag.Id, Items.Container.GreenBag },
            { Items.Container.GreyBag.Id, Items.Container.GreyBag },
            { Items.Container.PurpleBag.Id, Items.Container.PurpleBag },
            { Items.Container.RedBag.Id, Items.Container.RedBag },
            { Items.Container.YellowBag.Id, Items.Container.YellowBag },
        };
        #endregion

        #region Backpacks
        public static Dictionary<uint, Item> Backpacks = new Dictionary<uint, Item>
        {
			{ Items.Container.GreyBackpack.Id, Items.Container.GreyBackpack },
			{ Items.Container.BlueBackpack.Id, Items.Container.BlueBackpack },
			{ Items.Container.NormalBackpack.Id, Items.Container.NormalBackpack },
            { Items.Container.BrocadeBackpack.Id, Items.Container.BrocadeBackpack },
			{ Items.Container.GoldenBackpack.Id, Items.Container.GoldenBackpack },
			{ Items.Container.CamouflageBackpack.Id, Items.Container.CamouflageBackpack },
			{ Items.Container.GreenBackpack.Id, Items.Container.GreenBackpack },
            { Items.Container.MoonBackpack.Id, Items.Container.MoonBackpack },
            { Items.Container.BackpackOfHolding.Id, Items.Container.BackpackOfHolding },
			{ Items.Container.PirateBackpack.Id, Items.Container.PirateBackpack },
			{ Items.Container.PurpleBackpack.Id, Items.Container.PurpleBackpack },
			{ Items.Container.RedBackpack.Id, Items.Container.RedBackpack },
			{ Items.Container.BeachBackpack.Id, Items.Container.BeachBackpack },
			{ Items.Container.YellowBackpack.Id, Items.Container.YellowBackpack },
            { Items.Container.KeyRing.Id, Items.Container.KeyRing },
        };
        #endregion

        #region Foods
        public static Dictionary<uint, Objects.Food> Foods = new Dictionary<uint, Objects.Food>
		{
			{ Items.Food.Apple.Id, Items.Food.Apple }, 
			{ Items.Food.Banana.Id, Items.Food.Banana }, 
			{ Items.Food.Blueberry.Id, Items.Food.Blueberry }, 
			{ Items.Food.Bread.Id, Items.Food.Bread }, 
			{ Items.Food.BrownBread.Id, Items.Food.BrownBread }, 
			{ Items.Food.BrownMushroom.Id, Items.Food.BrownMushroom }, 
			{ Items.Food.Carrot.Id, Items.Food.Carrot }, 
			{ Items.Food.Cheese.Id, Items.Food.Cheese }, 
			{ Items.Food.Cherry.Id, Items.Food.Cherry }, 
			{ Items.Food.Coconut.Id, Items.Food.Coconut }, 
			{ Items.Food.Cookie.Id, Items.Food.Cookie }, 
			{ Items.Food.Corncob.Id, Items.Food.Corncob }, 
			{ Items.Food.DragonHam.Id, Items.Food.DragonHam }, 
			{ Items.Food.Egg.Id, Items.Food.Egg }, 
			{ Items.Food.Fish.Id, Items.Food.Fish }, 
			{ Items.Food.Grapes.Id, Items.Food.Grapes }, 
			{ Items.Food.GreenMushroom.Id, Items.Food.GreenMushroom }, 
			{ Items.Food.Ham.Id, Items.Food.Ham }, 
			{ Items.Food.Meat.Id, Items.Food.Meat }, 
			{ Items.Food.Mellon.Id, Items.Food.Mellon }, 
			{ Items.Food.Orange.Id, Items.Food.Orange }, 
			{ Items.Food.Roll.Id, Items.Food.Roll }, 
			{ Items.Food.Salmon.Id, Items.Food.Salmon }, 
			{ Items.Food.WhiteMushroom.Id, Items.Food.WhiteMushroom },
        };
        #endregion

        #region Quest Pieces
        public static Dictionary<uint, Item> QuestPieces = new Dictionary<uint, Item>
		{
			{ Items.Quest.ApeFur.Id, Items.Quest.ApeFur }, 
			{ Items.Quest.BatWing.Id, Items.Quest.BatWing }, 
			{ Items.Quest.BearPaw.Id, Items.Quest.BearPaw }, 
			{ Items.Quest.BeholderEye.Id, Items.Quest.BeholderEye }, 
			{ Items.Quest.BluePieceofCloth.Id, Items.Quest.BluePieceofCloth }, 
			{ Items.Quest.BrownPieceofCloth.Id, Items.Quest.BrownPieceofCloth }, 
			{ Items.Quest.ChickenFeather.Id, Items.Quest.ChickenFeather }, 
			{ Items.Quest.DragonClaw.Id, Items.Quest.DragonClaw }, 
			{ Items.Quest.EyePatch.Id, Items.Quest.EyePatch },
			{ Items.Quest.FishFin.Id, Items.Quest.FishFin }, 
			{ Items.Quest.GreenDragonLeather.Id, Items.Quest.GreenDragonLeather }, 
			{ Items.Quest.GreenDragonScale.Id, Items.Quest.GreenDragonScale }, 
			{ Items.Quest.GreenPieceofCloth.Id, Items.Quest.GreenPieceofCloth }, 
			{ Items.Quest.HeavenBlossom.Id, Items.Quest.HeavenBlossom }, 
			{ Items.Quest.Hook.Id, Items.Quest.Hook },
			{ Items.Quest.HoneyComb.Id, Items.Quest.HoneyComb }, 
			{ Items.Quest.LizardLeather.Id, Items.Quest.LizardLeather }, 
			{ Items.Quest.LizardScale.Id, Items.Quest.LizardScale }, 
			{ Items.Quest.MinotaurLeather.Id, Items.Quest.MinotaurLeather }, 
			{ Items.Quest.PegLeg.Id, Items.Quest.PegLeg },
			{ Items.Quest.RedDragonLeather.Id, Items.Quest.RedDragonLeather }, 
			{ Items.Quest.RedDragonScale.Id, Items.Quest.RedDragonScale }, 
			{ Items.Quest.RedPieceofCloth.Id, Items.Quest.RedPieceofCloth }, 
			{ Items.Quest.SniperGloves.Id, Items.Quest.SniperGloves }, 
			{ Items.Quest.VampireDust.Id, Items.Quest.VampireDust }, 
			{ Items.Quest.WhitePieceofCloth.Id, Items.Quest.WhitePieceofCloth }, 
			{ Items.Quest.WolfPaw.Id, Items.Quest.WolfPaw }, 
			{ Items.Quest.YellowPieceofCloth.Id, Items.Quest.YellowPieceofCloth },
        };
        #endregion

        #region Tools
        public static Dictionary<uint, Item> Tools = new Dictionary<uint, Item>
		{
			{ Items.Tool.Rope.Id, Items.Tool.Rope }, 
			{ Items.Tool.FishingRod.Id, Items.Tool.FishingRod }, 
			{ Items.Tool.Pick.Id, Items.Tool.Pick }, 
			{ Items.Tool.Shovel.Id, Items.Tool.Shovel },
			{ Items.Tool.Scythe.Id, Items.Tool.Scythe },
            { Items.Tool.LightShovel.Id, Items.Tool.LightShovel },
            { Items.Tool.ElvenhairRope.Id, Items.Tool.ElvenhairRope },
        };
        #endregion

        #region Valuables
        public static Dictionary<uint, Item> Valuables = new Dictionary<uint, Item>
		{
			{ Items.Valuable.GoldCoin.Id, Items.Valuable.GoldCoin }, 
			{ Items.Valuable.PlatinumCoin.Id, Items.Valuable.PlatinumCoin }, 
			{ Items.Valuable.CrystalCoin.Id, Items.Valuable.CrystalCoin }, 
			{ Items.Valuable.ScarabCoin.Id, Items.Valuable.ScarabCoin }, 
			{ Items.Valuable.SmallAmethyst.Id, Items.Valuable.SmallAmethyst }, 
			{ Items.Valuable.SmallEmerald.Id, Items.Valuable.SmallEmerald }, 
			{ Items.Valuable.BlackPearl.Id, Items.Valuable.BlackPearl }, 
			{ Items.Valuable.WhitePearl.Id, Items.Valuable.WhitePearl },
        };
        #endregion

        #region Bottles
        public static Dictionary<uint, Item> Bottles = new Dictionary<uint, Item>
		{			
			{ Items.Bottle.Vial.Id, Items.Bottle.Vial },
        };
        #endregion

        #region Health Potions
        public static Dictionary<uint, Item> HealthPotions = new Dictionary<uint, Item>
		{
			{ Items.Potion.Health.Id, Items.Potion.Health }, 
			{ Items.Potion.StrongHealth.Id, Items.Potion.StrongHealth }, 
			{ Items.Potion.GreatHealth.Id, Items.Potion.GreatHealth }, 
			{ Items.Potion.UltimateHealth.Id, Items.Potion.UltimateHealth },
        };
        #endregion

        #region Mana Potions
        public static Dictionary<uint, Item> ManaPotions = new Dictionary<uint, Item>
		{
			{ Items.Potion.Mana.Id, Items.Potion.Mana }, 
			{ Items.Potion.StrongMana.Id, Items.Potion.StrongMana }, 
			{ Items.Potion.GreatMana.Id, Items.Potion.GreatMana },
        };
        #endregion

        #region Spirit Potions
        public static Dictionary<uint, Item> SpiritPotions = new Dictionary<uint, Item>
		{
			{ Items.Potion.GreatSpirit.Id, Items.Potion.GreatSpirit },
        };
        #endregion

        #region Rings
        public static Dictionary<uint, Item> Rings = new Dictionary<uint, Item>
		{
			{ Items.Ring.AxeRing.Id, Items.Ring.AxeRing },
			{ Items.Ring.ClubRing.Id, Items.Ring.ClubRing },
			{ Items.Ring.CrystalRing.Id, Items.Ring.CrystalRing },
			{ Items.Ring.DwarvenRing.Id, Items.Ring.DwarvenRing },
			{ Items.Ring.EnergyRing.Id, Items.Ring.EnergyRing },
			{ Items.Ring.LifeRing.Id, Items.Ring.LifeRing },
			{ Items.Ring.MightRing.Id, Items.Ring.MightRing },
			{ Items.Ring.PowerRing.Id, Items.Ring.PowerRing },
			{ Items.Ring.RingOfHealing.Id, Items.Ring.RingOfHealing },
			{ Items.Ring.RingOfTheSkies.Id, Items.Ring.RingOfTheSkies },
			{ Items.Ring.StealthRing.Id, Items.Ring.StealthRing },
			{ Items.Ring.TimeRing.Id, Items.Ring.TimeRing },
        };
        #endregion

        #region Runes
        public static Dictionary<uint, Rune> Runes = new Dictionary<uint, Rune>
        {
			{ Items.Rune.AnimateDead.Id, Items.Rune.AnimateDead },
			{ Items.Rune.Antidote.Id, Items.Rune.Antidote },
			{ Items.Rune.Avalanche.Id, Items.Rune.Avalanche },
			{ Items.Rune.Chameleon.Id, Items.Rune.Chameleon },
			{ Items.Rune.ConvinceCreature.Id, Items.Rune.ConvinceCreature },
			{ Items.Rune.Desintegrate.Id, Items.Rune.Desintegrate },
			{ Items.Rune.DestroyField.Id, Items.Rune.DestroyField },
			{ Items.Rune.EnergyBomb.Id, Items.Rune.EnergyBomb },
			{ Items.Rune.EnergyField.Id, Items.Rune.EnergyField },
			{ Items.Rune.EnergyWall.Id, Items.Rune.EnergyWall },
			{ Items.Rune.Explosion.Id, Items.Rune.Explosion },
			{ Items.Rune.FireBomb.Id, Items.Rune.FireBomb },
			{ Items.Rune.FireField.Id, Items.Rune.FireField },
			{ Items.Rune.FireWall.Id, Items.Rune.FireWall },
			{ Items.Rune.Fireball.Id, Items.Rune.Fireball },
			{ Items.Rune.GreatFireball.Id, Items.Rune.GreatFireball },
			{ Items.Rune.HeavyMagicMissile.Id, Items.Rune.HeavyMagicMissile },
			{ Items.Rune.Icicle.Id, Items.Rune.Icicle },
			{ Items.Rune.IntenseHealing.Id, Items.Rune.IntenseHealing },
			{ Items.Rune.LightMagicMissile.Id, Items.Rune.LightMagicMissile },
			{ Items.Rune.MagicWall.Id, Items.Rune.MagicWall },
			{ Items.Rune.Paralyze.Id, Items.Rune.Paralyze },
			{ Items.Rune.PoisonBomb.Id, Items.Rune.PoisonBomb },
			{ Items.Rune.PoisonField.Id, Items.Rune.PoisonField },
			{ Items.Rune.PoisonWall.Id, Items.Rune.PoisonWall },
			{ Items.Rune.Soulfire.Id, Items.Rune.Soulfire },
			{ Items.Rune.Stalagmite.Id, Items.Rune.Stalagmite },
			{ Items.Rune.StoneShower.Id, Items.Rune.StoneShower },
			{ Items.Rune.SuddenDeath.Id, Items.Rune.SuddenDeath },
			{ Items.Rune.Thunderstorm.Id, Items.Rune.Thunderstorm },
			{ Items.Rune.UltimateHealing.Id, Items.Rune.UltimateHealing },
        };
        #endregion
    }
}
