using System;
using Tibia.Objects;

namespace Tibia.Constants
{
    public static class Spells
    {
        public static Spell AnimateDead = new Spell("Animate Dead", "adana mort", 600, SpellCategory.Summon, SpellType.ItemTransformation);
        public static Spell Antidote = new Spell("Antidote", "exana pox", 30, SpellCategory.Healing, SpellType.Instant);
        public static Spell AntidoteRune = new Spell("Antidote Rune", "adana pox", 200, SpellCategory.Healing, SpellType.ItemTransformation);
        public static Spell AvalancheRune = new Spell("Avalanche Rune", "adori mas frigo", 530, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell Berserk = new Spell("Berserk", "exori", 115, SpellCategory.Attack, SpellType.Instant);
        public static Spell CancelInvisibility = new Spell("Cancel Invisibility", "exana ina", 200, SpellCategory.Support, SpellType.Instant);
        public static Spell Challenge = new Spell("Challenge", "exeta res", 30, SpellCategory.Support, SpellType.Instant);
        public static Spell Chameleon = new Spell("Chameleon", "adevo ina", 600, SpellCategory.Support, SpellType.ItemTransformation);
        public static Spell ConjureArrow = new Spell("Conjure Arrow", "exevo con", 100, SpellCategory.Supply, SpellType.Instant);
        public static Spell ConjureBolt = new Spell("Conjure Bolt", "exevo con mort", 140, SpellCategory.Supply, SpellType.Instant);
        public static Spell ConjurePiercingBolt = new Spell("Conjure Piercing Bolt", "exevo con grav", 180, SpellCategory.Supply, SpellType.Instant);
        public static Spell ConjureSniperArrow = new Spell("Conjure Sniper Arrow", "exevo con hur", 160, SpellCategory.Supply, SpellType.Instant);
        public static Spell ConvinceCreature = new Spell("Convince Creature", "adeta sio", 200, SpellCategory.Summon, SpellType.ItemTransformation);
        public static Spell CreatureIllusion = new Spell("Creature Illusion", "utevo res ina \"{creatureName}\"", 100, SpellCategory.Support, SpellType.Instant);
        public static Spell Desintegrate = new Spell("Desintegrate", "adito tera", 200, SpellCategory.Support, SpellType.ItemTransformation);
        public static Spell DestroyField = new Spell("Destroy Field", "adito grav", 120, SpellCategory.Support, SpellType.ItemTransformation);
        public static Spell EnchantSpear = new Spell("Enchant Spear", "exeta con", 350, SpellCategory.Supply, SpellType.ItemTransformation);
        public static Spell EnchantStaff = new Spell("Enchant Staff", "exeta vis", 80, SpellCategory.Supply, SpellType.Instant);
        public static Spell EnergyBeam = new Spell("Energy Beam", "exevo vis lux", 40, SpellCategory.Attack, SpellType.Instant);
        public static Spell EnergyField = new Spell("Energy Field", "adevo grav vis", 320, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell EnergyStrike = new Spell("Energy Strike", "exori vis", 20, SpellCategory.Attack, SpellType.Instant);
        public static Spell EnergyWall = new Spell("Energy Wall", "adevo mas grav vis", 1000, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell EnergyWave = new Spell("Energy Wave", "exevo mort hur", 170, SpellCategory.Attack, SpellType.Instant);
        public static Spell EnergyBomb = new Spell("Energybomb", "adevo mas vis", 880, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell EternalWinter = new Spell("Eternal Winter", "exevo gran mas frigo", 1200, SpellCategory.Attack, SpellType.Instant);
        public static Spell EtherealSpear = new Spell("Ethereal Spear", "exori con", 25, SpellCategory.Attack, SpellType.Instant);
        public static Spell Explosion = new Spell("Explosion", "adevo mas hur", 570, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell ExplosiveArrow = new Spell("Explosive Arrow", "exevo con flam", 290, SpellCategory.Supply, SpellType.Instant);
        public static Spell FierceBerserk = new Spell("Fierce Berserk", "exori gran", 340, SpellCategory.Attack, SpellType.Instant);
        public static Spell FindPerson = new Spell("Find Person", "exiva \"{name}\"", 20, SpellCategory.Support, SpellType.Instant);
        public static Spell FireField = new Spell("Fire Field", "adevo grav flam", 240, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell FireWall = new Spell("Fire Wall", "adevo mas grav flam", 780, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell FireWave = new Spell("Fire Wave", "exevo flam hur", 25, SpellCategory.Attack, SpellType.Instant);
        public static Spell Fireball = new Spell("Fireball", "adori flam", 460, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell FireBomb = new Spell("Firebomb", "adevo mas flam", 600, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell FlameStrike = new Spell("Flame Strike", "exori flam", 20, SpellCategory.Attack, SpellType.Instant);
        public static Spell Food = new Spell("Food", "exevo pan", 120, SpellCategory.Supply, SpellType.Instant);
        public static Spell ForceStrike = new Spell("Force Strike", "exori mort", 20, SpellCategory.Attack, SpellType.Instant);
        public static Spell GreatEnergyBeam = new Spell("Great Energy Beam", "exevo gran vis lux", 110, SpellCategory.Attack, SpellType.Instant);
        public static Spell GreatFireball = new Spell("Great Fireball", "adori mas flam", 530, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell GreatLight = new Spell("Great Light", "utevo gran lux", 60, SpellCategory.Support, SpellType.Instant);
        public static Spell Groundshaker = new Spell("Groundshaker", "exori mas", 160, SpellCategory.Attack, SpellType.Instant);
        public static Spell Haste = new Spell("Haste", "utani hur", 60, SpellCategory.Support, SpellType.Instant);
        public static Spell HealFriend = new Spell("Heal Friend", "exura sio \"{name}\"", 140, SpellCategory.Healing, SpellType.Instant);
        public static Spell HeavyMagicMissile = new Spell("Heavy Magic Missile", "adori vis", 350, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell HellsCore = new Spell("Hell's Core", "exevo gran mas flam", 1200, SpellCategory.Attack, SpellType.Instant);
        public static Spell Icicle = new Spell("Icicle", "adori frigo", 460, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell IntenseHealing = new Spell("Intense Healing", "exura gran", 70, SpellCategory.Healing, SpellType.Instant);
        public static Spell IntenseHealingRune = new Spell("Intense Healing Rune", "adura gran", 120, SpellCategory.Healing, SpellType.ItemTransformation);
        public static Spell Invisible = new Spell("Invisible", "utana vid", 440, SpellCategory.Support, SpellType.Instant);
        public static Spell Levitate = new Spell("Levitate", "exani hur \"{up|down}\"", 50, SpellCategory.Support, SpellType.Instant);
        public static Spell Light = new Spell("Light", "utevo lux", 20, SpellCategory.Support, SpellType.Instant);
        public static Spell LightHealing = new Spell("Light Healing", "exura", 20, SpellCategory.Healing, SpellType.Instant);
        public static Spell LightMagicMissile = new Spell("Light Magic Missile", "adori min vis", 120, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell MagicRope = new Spell("Magic Rope", "exani tera", 20, SpellCategory.Support, SpellType.Instant);
        public static Spell MagicShield = new Spell("Magic Shield", "utamo vita", 50, SpellCategory.Support, SpellType.Instant);
        public static Spell MagicWall = new Spell("Magic Wall", "adevo grav tera", 750, SpellCategory.Support, SpellType.ItemTransformation);
        public static Spell MassHealing = new Spell("Mass Healing", "exura gran mas res", 150, SpellCategory.Healing, SpellType.Instant);
        public static Spell Paralyze = new Spell("Paralyze", "adana ani", 1400, SpellCategory.Support, SpellType.ItemTransformation);
        public static Spell PoisonBomb = new Spell("Poison Bomb", "adevo mas pox", 520, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell PoisonField = new Spell("Poison Field", "adevo grav pox", 200, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell PoisonWall = new Spell("Poison Wall", "adevo mas grav pox", 640, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell PoisonedArrow = new Spell("Poisoned Arrow", "exevo con pox", 130, SpellCategory.Supply, SpellType.Instant);
        public static Spell PowerBolt = new Spell("Power Bolt", "exevo con vis", 700, SpellCategory.Supply, SpellType.Instant);
        public static Spell RageoftheSkies = new Spell("Rage of the Skies", "exevo gran mas vis", 650, SpellCategory.Attack, SpellType.Instant);
        public static Spell Soulfire = new Spell("Soulfire", "adevo res flam", 420, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell Stalagmite = new Spell("Stalagmite", "adori tera", 350, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell StoneShower = new Spell("Stone Shower", "adori mas tera", 430, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell StrongHaste = new Spell("Strong Haste", "utani gran hur", 100, SpellCategory.Support, SpellType.Instant);
        public static Spell SuddenDeath = new Spell("Sudden Death", "adori gran mort", 985, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell SummonCreature = new Spell("Summon Creature", "utevo res \"{creatureName}\"", 0, SpellCategory.Summon, SpellType.Instant);
        public static Spell Thunderstorm = new Spell("Thunderstorm", "adori mas vis", 430, SpellCategory.Attack, SpellType.ItemTransformation);
        public static Spell UltimateExplosion = new Spell("Ultimate Explosion", "exevo gran mas vis", 1200, SpellCategory.Attack, SpellType.Instant);
        public static Spell UltimateHealing = new Spell("Ultimate Healing", "exura vita", 160, SpellCategory.Healing, SpellType.Instant);
        public static Spell UltimateHealingRune = new Spell("Ultimate Healing Rune", "adura vita", 400, SpellCategory.Healing, SpellType.ItemTransformation);
        public static Spell UltimateLight = new Spell("Ultimate Light", "utevo vis lux", 140, SpellCategory.Support, SpellType.Instant);
        public static Spell UndeadLegion = new Spell("Undead Legion", "exana mas mort", 500, SpellCategory.Summon, SpellType.Instant);
        public static Spell WhirlwindThrow = new Spell("Whirlwind Throw", "exori hur", 40, SpellCategory.Attack, SpellType.Instant);
        public static Spell WildGrowth = new Spell("Wild Growth", "exevo grav vita", 220, SpellCategory.Support, SpellType.Instant);
        public static Spell WoundCleanse = new Spell("Wound Cleanse", "exana mort", 65, SpellCategory.Healing, SpellType.Instant);
        public static Spell WrathofNature = new Spell("Wrath of Nature", "exevo gran mas tera", 770, SpellCategory.Attack, SpellType.Instant);
    }
}